# -*- coding: utf-8 -*-
"""Lump sum Investing vs Dollar Cost Averaging.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16qKv9TIsyT_uYWPxtXUODXCII7QagoCL
"""



"""# Lump sum investing  with direct reinvesting of dividend."""

import sys
import datetime as dt
from dateutil.relativedelta import relativedelta
import numpy as np
import pandas as pd
import yfinance as yf

# Le script imprime des caractères hors ASCII (✓, ✗, ─, α, Δ, €...). Sur
# Windows, la console hérite par défaut de l'encodage cp1252 et lève une
# UnicodeEncodeError dès le premier caractère non représentable. On force
# stdout/stderr en UTF-8 pour que le script tourne à l'identique sous
# Colab (déjà UTF-8) et en local Windows.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8")


def simulate_lump_sum_drip_fractional(ticker_str, w0, t0_str, tf_str=None):
    """Simule une stratégie Lump Sum avec réinvestissement automatique des dividendes (DRIP)

    en utilisant des actions fractionnées (l'intégralité de l'argent est investie).
    """
    # 1. Gestion des dates
    t0 = dt.datetime.strptime(t0_str, "%Y-%m-%d")
    if tf_str is None:
        tf = t0 + relativedelta(years=5)
    else:
        tf = dt.datetime.strptime(tf_str, "%Y-%m-%d")

    # Téléchargement de l'historique
    ticker = yf.Ticker(ticker_str)
    df = ticker.history(start=t0, end=tf + dt.timedelta(days=5))

    if df.empty:
        raise ValueError(
            f"Aucune donnée trouvée pour le ticker {ticker_str} sur cette période."
        )

    # Suppression du fuseau horaire pour éviter le bug de comparaison
    if df.index.tz is not None:
        df.index = df.index.tz_localize(None)

    # Filtrer strictement entre t0 et tf
    df = df.loc[t0:tf]

    if df.empty:
        raise ValueError(
            f"Le segment de données entre {t0_str} et {tf.strftime('%Y-%m-%d')} est vide."
        )

    # 2. Investissement Initial à t0 (Tout est investi, pas d'arrondi)
    initial_row = df.iloc[0]
    p_init = initial_row["Open"]  # Achat au prix d'ouverture
    t0_actual = df.index[0]

    shares = w0 / p_init  # Nombre de parts exact (avec virgule)
    cash = 0.0  # Par définition, tout est investi

    print(f"--- Investissement Initial ({t0_actual.strftime('%Y-%m-%d')}) ---")
    print(f"Prix d'ouverture : {p_init:.2f}$")
    print(f"Parts achetées   : {shares:.6f}")
    print(f"Solde cash       : {cash:.2f}$\n")

    # 3. Gestion des dividendes et réinvestissement fractionné
    div_events = df[df["Dividends"] > 0]

    print("--- Suivi des dividendes et réinvestissements (Fractions) ---")
    for date, row in div_events.iterrows():
        div_per_share = row["Dividends"]
        p_reinvest = row["Close"]

        # Tout le cash reçu des dividendes est réinvesti
        total_div_received = shares * div_per_share

        # Nouvelles fractions d'actions achetées
        new_fractions = total_div_received / p_reinvest
        shares += new_fractions  # S'ajoute directement au portefeuille

        print(
            f"[{date.strftime('%Y-%m-%d')}] Div/Part: {div_per_share:.3f}$ | Recu: {total_div_received:.2f}$ | "
            f"+{new_fractions:.6f} parts à {p_reinvest:.2f}$ | Total Parts: {shares:.6f}"
        )

    # 4. Évaluation Finale à tf
    final_row = df.iloc[-1]
    p_final = final_row["Close"]  # Valeur à la dernière clôture
    tf_actual = df.index[-1]

    w_final = shares * p_final

    # 5. Calcul des Métriques
    total_return = (w_final - w0) / w0
    years = (tf_actual - t0_actual).days / 365.25
    cagr = (w_final / w0) ** (1 / years) - 1 if years > 0 else np.nan

    metrics = {
        "Ticker": ticker_str,
        "Date Initiale": t0_actual.strftime("%Y-%m-%d"),
        "Date Finale": tf_actual.strftime("%Y-%m-%d"),
        "Capital Initial ($)": w0,
        "Capital Final ($)": w_final,
        "Parts Finales": shares,
        "Cash Final ($)": cash,
        "Rendement Total (%)": total_return * 100,
        "CAGR (%)": cagr * 100,
    }

    return metrics

"""## 1-1 Test de cette fonction Lump Sum investing"""

# --- EXEMPLE D'UTILISATION ---
if __name__ == "__main__":
    ticker_exemple = "SPY"
    capital_initial = 10000
    date_debut = "2000-02-10"

    resultats = simulate_lump_sum_drip_fractional(
        ticker_str=ticker_exemple, w0=capital_initial, t0_str=date_debut,tf_str = "2016-01-09"
    )

    print("\n--- METRIQUES DE PERFORMANCE FINALE ---")
    for k, v in resultats.items():
        if isinstance(v, float):
            print(f"{k:<25} : {v:.4f}")
        else:
            print(f"{k:<25} : {v}")

# --- EXEMPLE D'UTILISATION ---
if __name__ == "__main__":
    ticker_exemple = "SPY"
    capital_initial = 10000
    date_debut = "2000-02-10"

    resultats = simulate_lump_sum_drip_fractional(
        ticker_str=ticker_exemple, w0=capital_initial, t0_str=date_debut,tf_str = "2000-02-10"
    )

    print("\n--- METRIQUES DE PERFORMANCE FINALE ---")
    for k, v in resultats.items():
        if isinstance(v, float):
            print(f"{k:<25} : {v:.4f}")
        else:
            print(f"{k:<25} : {v}")

import yfinance as yf

# Téléchargement des données pour la journée spécifique
spy_data = yf.download("SPY", start="2000-02-10", end="2000-02-11")

spy_data

import yfinance as yf

# Téléchargement des données pour la journée spécifique
spy_data = yf.download("SPY", start="2000-02-11", end="2000-02-12")

spy_data

# Téléchargement des données pour la journée spécifique
spy_data = yf.download("SPY", start="2000-02-11", end="2000-02-12")

spy_data

"""1- Le rsultat est bien le bon , car en le prmier jour de l'investissement il achete au prix Open et le programme s'arrete avec le prix au Close. On trouve bien que le capital restant est perte ( prix close - prix open)nombre de part + Capital initial

2- Maintenant tester le cas ou il y'a un paiement de dividende.

# Dollar Cost averaging
"""

import datetime as dt
from dateutil.relativedelta import relativedelta
import numpy as np
import pandas as pd
import yfinance as yf


def simulate_dca_drip_fractional(ticker_str, w0, t0_str, tf_str=None, freq="M"):
    """Simule une stratégie de Dollar Cost Averaging (DCA) avec réinvestissement

    automatique des dividendes (DRIP) en utilisant des actions fractionnées.

    Parameters:
    -----------
    ticker_str : str
        Le ticker de l'action (ex: 'AAPL', 'MSFT').
    w0 : float
        Le capital total initial à diviser et à déployer.
    t0_str : str
        La date de départ au format 'YYYY-MM-DD'.
    tf_str : str, optional
        La date de fin au format 'YYYY-MM-DD'. Par défaut, t0 + 5 ans.
    freq : str, optional
        La fréquence d'investissement :
        'D' (Journalier), 'W' (Hebdomadaire), 'M' (Mensuel),
        'Q' (Trimestriel), 'S' (Semestriel), 'A' (Annuel).

    Returns:
    --------
    dict
        Métriques de performance et statistiques sur le nombre d'investissements.
    """
    # 1. Gestion et parsing des dates
    t0 = dt.datetime.strptime(t0_str, "%Y-%m-%d")
    if tf_str is None:
        tf = t0 + relativedelta(years=5)
    else:
        tf = dt.datetime.strptime(tf_str, "%Y-%m-%d")

    # Mappage des fréquences pour les adapter au générateur de calendrier Pandas (DatetimeIndex)
    freq_map = {
        "D": "B",  # 'B' = Business day (jours ouvrés, évite les week-ends)
        "W": "W-MON",  # Chaque lundi
        "M": "MS",  # 'MS' = Month Start (premier jour du mois)
        "Q": "BQS",  # 'BQS' = Business Quarter Start
        "S": "6MS",  # Tous les 6 mois (Semestriel)
        "A": "BYS",  # 'BYS' = Business Year Start
    }

    if freq.upper() not in freq_map:
        raise ValueError(
            f"Fréquence indésirable. Choisissez parmi : {list(freq_map.keys())}"
        )

    pandas_freq = freq_map[freq.upper()]

    # Génération du calendrier théorique des dates d'investissement
    # t1 = t0, tN = tf
    investment_dates = pd.date_range(start=t0, end=tf, freq=pandas_freq)

    # N est le nombre total de tranches d'investissement
    N = len(investment_dates)
    if N == 0:
        raise ValueError(
            "Le calendrier d'investissement est vide. Vérifiez l'écart entre t0 et tf."
        )

    # Calcul de la valeur de chaque tranche de déploiement
    w_tranche = w0 / N

    # 2. Téléchargement et alignement des données financières
    ticker = yf.Ticker(ticker_str)
    df = ticker.history(start=t0, end=tf + dt.timedelta(days=5))

    if df.empty:
        raise ValueError(f"Aucune donnée trouvée pour le ticker {ticker_str}.")

    # Suppression des fuseaux horaires
    if df.index.tz is not None:
        df.index = df.index.tz_localize(None)

    # Filtrage strict de la plage de l'historique
    df = df.loc[t0:tf]

    # 3. Ajustement des dates d'investissement aux jours réels de cotation du marché
    # Si une date théorique tombe un jour de fermeture, on prend le premier jour ouvré disponible
    actual_investment_dates = []
    for d in investment_dates:
        # Trouver la première date dans le DataFrame supérieure ou égale à 'd'
        available_dates = df.index[df.index >= d]
        if not available_dates.empty:
            actual_investment_dates.append(available_dates[0])

    # Supprimer les doublons potentiels d'alignement
    actual_investment_dates = sorted(list(set(actual_investment_dates)))

    # On met à jour N et la tranche si l'alignement marché a réduit le nombre de dates réelles
    N = len(actual_investment_dates)
    w_tranche = w0 / N

    print(f"--- CONFIGURATION DU PLAN DCA ---")
    print(f"Nombre total d'investissements prévus (N) : {N}")
    print(f"Montant injecté à chaque occurrence (w)   : {w_tranche:.2f}$\n")

    # 4. Exécution de la simulation chronologique
    shares = 0.0
    total_invested_so_far = 0.0

    print("--- JOURNAL DES OPÉRATIONS (DCA + DRIP) ---")

    # Parcourir chaque jour de bourse chronologiquement
    for date, row in df.iterrows():

        # Cas A : C'est une date d'investissement DCA
        if date in actual_investment_dates:
            p_buy = row["Open"]  # Achat au prix d'ouverture prévu
            new_shares_dca = w_tranche / p_buy
            shares += new_shares_dca
            total_invested_so_far += w_tranche
            print(
                f"[{date.strftime('%Y-%m-%d')}] [DCA] Ingestion de {w_tranche:.2f}$ | "
                f"Achat de {new_shares_dca:.6f} parts à {p_buy:.2f}$ | Total parts : {shares:.6f}"
            )

        # Cas B : Un dividende est payé ce jour-là (DRIP)
        if row["Dividends"] > 0 and shares > 0:
            div_per_share = row["Dividends"]
            p_reinvest = row["Close"]  # Réinvestissement au prix de clôture

            total_div_received = shares * div_per_share
            new_shares_div = total_div_received / p_reinvest
            shares += new_shares_div
            print(
                f"[{date.strftime('%Y-%m-%d')}] [DRIP] Dividende reçu : {total_div_received:.2f}$ | "
                f"Réinvesti en {new_shares_div:.6f} parts à {p_reinvest:.2f}$ | Total parts : {shares:.6f}"
            )

    # 5. Évaluation finale à la clôture de la période
    final_row = df.iloc[-1]
    p_final = final_row["Close"]
    t0_actual = df.index[0]
    tf_actual = df.index[-1]

    w_final = shares * p_final
    total_return = (w_final - w0) / w0

    # Calcul du CAGR basé sur la durée réelle écoulée
    years = (tf_actual - t0_actual).days / 365.25
    cagr = (w_final / w0) ** (1 / years) - 1 if years > 0 else np.nan

    metrics = {
        "Ticker": ticker_str,
        "Fréquence": freq.upper(),
        "Nombre d'investissements (N)": N,
        "Montant par tranche ($)": w_tranche,
        "Date Initiale Réelle": t0_actual.strftime("%Y-%m-%d"),
        "Date Finale Réelle": tf_actual.strftime("%Y-%m-%d"),
        "Capital Initial ($)": w0,
        "Capital Final ($)": w_final,
        "Parts Accumulées Finales": shares,
        "Rendement Total (%)": total_return * 100,
        "CAGR (%)": cagr * 100,
    }

    return metrics

# --- EXÉCUTION DE TON SCÉNARIO ---
if __name__ == "__main__":

    # Configuration stricte selon tes critères
    resultats = simulate_dca_drip_fractional(
        ticker_str="MSFT",
        w0=10000,               # <--- Ton montant initial
        t0_str="2020-01-15",    # <--- Ta date de début
        tf_str="2025-01-15",    # <--- Ta date de fin
        freq="M"                # <--- Fréquence (Modulable en 'D', 'W', 'M', 'Q', 'S', 'A')
    )

    print("\n--- METRIQUES DE PERFORMANCE FINALE ---")
    for k, v in resultats.items():
        if isinstance(v, float):
            print(f"{k:<32} : {v:.4f}")
        else:
            print(f"{k:<32} : {v}")

# --- EXÉCUTION DE TON SCÉNARIO ---
if __name__ == "__main__":

    # Configuration stricte selon tes critères
    resultats = simulate_dca_drip_fractional(
        ticker_str="MSFT",
        w0=10000,               # <--- Ton montant initial
        t0_str="2020-01-15",    # <--- Ta date de début
        tf_str="2020-02-15",    # <--- Ta date de fin
        freq="M"                # <--- Fréquence (Modulable en 'D', 'W', 'M', 'Q', 'S', 'A')
    )

    print("\n--- METRIQUES DE PERFORMANCE FINALE ---")
    for k, v in resultats.items():
        if isinstance(v, float):
            print(f"{k:<32} : {v:.4f}")
        else:
            print(f"{k:<32} : {v}")

"""# Methode de Mon article( Lump Sum unitaire + DCA - Rolling windows)

=============================================================================
DCA vs LSI — Analyse comparative par fenêtre glissante (Rolling Window)
=============================================================================

Architecture procédurale à quatre couches :

  COUCHE 0 — Données :
    fetch_price_history()                → téléchargement + nettoyage OHLCV

  COUCHE 1 — Simulation atomique :
    simulate_lump_sum_drip_fractional()  → retourne {metrics, equity_curve} LSI
    simulate_dca_drip_fractional()       → retourne {metrics, equity_curve} DCA

  COUCHE 2 — Métriques par fenêtre :
    compute_hpr()                        → Holding Period Return
    compute_sharpe_sortino()             → Sharpe & Sortino annualisés

  COUCHE 2b — Agrégation rolling :
    run_rolling_window_analysis()        → DataFrame N fenêtres × métriques
    compute_summary_statistics()         → stats descriptives (mean/std/min/med/max)
    run_statistical_tests()              → Mann-Whitney U, Kruskal-Wallis, Wilcoxon pairé

  COUCHE 3 — Visualisations (lazy : aucune ne s'affiche sans appel explicite) :
    plot_violin_hpr()                    → violins LSI vs DCA pour HPR, Sharpe, Sortino
    plot_scatter_temporal()              → HPR dans le temps selon le point d'entrée t0
    plot_hpr_diff_vs_market()            → HPR_diff vs niveau de marché à t0
    plot_sharpe_temporal()               → Sharpe ratio dans le temps
    plot_win_rate_bar()                  → barre % fenêtres où LSI > DCA par métrique
    plot_hpr_diff_distribution()         → distribution de HPR_LSI - HPR_DCA
    table_top_bottom_windows()           → DataFrame top/bottom N fenêtres par HPR_diff
    table_regime_breakdown()             → stats par régime marché (haussier/baissier)

  COUCHE 4 — Programme principal :
    main_comparison()                    → orchestre tout, retourne output dict

Flux d'exécution de main_comparison :
  run_rolling_window_analysis()
    ├─ simulate_lump_sum_drip_fractional()  ×N
    ├─ simulate_dca_drip_fractional()       ×N
    ├─ compute_hpr()                        ×2N
    └─ compute_sharpe_sortino()             ×2N
  compute_summary_statistics()
  run_statistical_tests()
  → retourne output dict (résultats + objets graphiques non affichés)

Utilisation des graphes :
  output["plots"]["violin_hpr"].show()
  output["plots"]["scatter_temporal"].show()
  # etc.
=============================================================================
"""

import datetime as dt
import warnings
from dateutil.relativedelta import relativedelta

import numpy as np
import pandas as pd
from scipy import stats
import yfinance as yf
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns

warnings.filterwarnings("ignore")

# Palette cohérente sur tous les graphes
_CLR_LSI = "#E63946"   # rouge
_CLR_DCA = "#457B9D"   # bleu acier
_CLR_DIFF = "#2A9D8F"  # vert sarcelle
_STYLE = "seaborn-v0_8-whitegrid"

import datetime as dt
import warnings
from dateutil.relativedelta import relativedelta

import numpy as np
import pandas as pd
from scipy import stats
import yfinance as yf
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns

warnings.filterwarnings("ignore")

# Palette cohérente sur tous les graphes
_CLR_LSI = "#E63946"   # rouge
_CLR_DCA = "#457B9D"   # bleu acier
_CLR_DIFF = "#2A9D8F"  # vert sarcelle
_STYLE = "seaborn-v0_8-whitegrid"


# =============================================================================
# COUCHE 0 — Utilitaires de données
# =============================================================================

def fetch_price_history(ticker_str: str, t0: dt.datetime, tf: dt.datetime) -> pd.DataFrame:
    """
    Télécharge et nettoie l'historique OHLCV + Dividendes d'un ticker sur [t0, tf].

    Rôle dans le flux global :
        Appelée par simulate_lsi et simulate_dca pour éviter la duplication.
        Chaque fenêtre glissante déclenche exactement deux appels (un par stratégie).

    Important — auto_adjust=False :
        yfinance renvoie par défaut (auto_adjust=True) des prix DÉJÀ ajustés
        des dividendes ET des splits. Le moteur de simulation réinvestit
        pourtant explicitement les dividendes via DRIP (colonne "Dividends",
        toujours brute quel que soit auto_adjust) — avec le défaut, cela
        comptait CHAQUE dividende deux fois (une fois dans le prix ajusté,
        une fois dans le DRIP manuel), gonflant artificiellement tous les
        HPR/CAGR/Sharpe. On force donc des prix bruts, et les splits sont
        gérés explicitement dans simulate_* via la colonne "Stock Splits".

    Returns
    -------
    pd.DataFrame — Index DatetimeIndex timezone-naive, colonnes OHLCV +
    Dividends + Stock Splits (prix bruts, non ajustés).
    """
    ticker = yf.Ticker(ticker_str)
    df = ticker.history(start=t0, end=tf + dt.timedelta(days=5), auto_adjust=False)

    if df.empty:
        raise ValueError(f"Aucune donnée pour {ticker_str} entre {t0.date()} et {tf.date()}.")

    if df.index.tz is not None:
        df.index = df.index.tz_localize(None)

    df = df.loc[t0:tf]

    if df.empty:
        raise ValueError(f"Segment vide pour {ticker_str} entre {t0.date()} et {tf.date()}.")

    return df


# =============================================================================
# Taux sans risque — rémunération du cash en attente (barème Livret A)
# =============================================================================
# Sous DCA, le capital pas encore investi n'est plus supposé dormir à 0% (biais
# reconnu en faveur du LSI dans la version initiale du papier). On le rémunère
# au taux sans risque le plus cohérent pour un particulier français plaçant du
# cash court terme, liquide et garanti : le Livret A (plutôt qu'un taux
# interbancaire type EONIA/€STR, inaccessible à un particulier). Barème
# officiel (arrêtés successifs, source Banque de France / Selectra / Magnolia) :
LIVRET_A_SCHEDULE = [
    ("2009-08-01", 0.0125),
    ("2010-08-01", 0.0175),
    ("2011-02-01", 0.0200),
    ("2011-08-01", 0.0225),
    ("2013-02-01", 0.0175),
    ("2013-08-01", 0.0125),
    ("2014-08-01", 0.0100),
    ("2015-08-01", 0.0075),
    ("2020-02-01", 0.0050),
    ("2022-02-01", 0.0100),
    ("2022-08-01", 0.0200),
    ("2023-02-01", 0.0300),
]
_LIVRET_A_DATES = pd.to_datetime([d for d, _ in LIVRET_A_SCHEDULE])
_LIVRET_A_RATES = np.array([r for _, r in LIVRET_A_SCHEDULE])


def get_livret_a_rate(date) -> float:
    """
    Taux annuel du Livret A en vigueur à `date`.

    En dehors du barème connu, on prolonge à plat la borne la plus proche
    (avant 2009-08-01 : 1.25% ; après 2023-02-01 : 3.00%) plutôt que
    d'échouer — les fenêtres de l'étude (2010-2020) sont toutes couvertes.
    """
    date = pd.Timestamp(date)
    idx = _LIVRET_A_DATES.searchsorted(date, side="right") - 1
    idx = max(0, min(idx, len(_LIVRET_A_RATES) - 1))
    return float(_LIVRET_A_RATES[idx])


# =============================================================================
# COUCHE 1 — Simulations atomiques
# =============================================================================

def simulate_lump_sum_drip_fractional(
    ticker_str: str,
    w0: float,
    t0_str: str,
    tf_str: str | None = None,
    verbose: bool = False,
) -> dict:
    """
    Simule la stratégie Lump Sum Investing (LSI) avec DRIP fractionné.

    Logique :
        - Tout le capital w0 est investi en une seule fois au prix d'ouverture de t0.
        - Chaque dividende est immédiatement réinvesti au prix de clôture (DRIP).
        - Actions fractionnées : pas d'arrondi, cash résiduel = 0.
        - Les splits ne nécessitent aucun traitement manuel : yfinance renvoie
          des prix TOUJOURS ajustés des splits (même avec auto_adjust=False,
          qui ne désactive que l'ajustement dividende) — un traitement
          manuel supplémentaire du ratio "Stock Splits" double-compterait
          l'effet, exactement comme le faisait le bug des dividendes.

    Important :
        La courbe d'equity est reconstruite jour par jour (et pas en multipliant
        le nombre de parts FINAL par toute la série de Close) : sinon, Sharpe et
        Sortino — qui utilisent les rendements journaliers de equity_curve —
        seraient calculés sur une série artificiellement constante en "nombre de
        parts", identique en pratique aux rendements du prix brut, et ignorant
        la vraie trajectoire de richesse (paliers aux dates de DRIP/split).

    Rôle dans le flux global :
        Appelée N fois par run_rolling_window_analysis(). Retourne equity_curve
        (pd.Series journalière) qui alimente compute_hpr() et compute_sharpe_sortino().

    Returns
    -------
    dict : {'metrics': dict, 'equity_curve': pd.Series}
    """
    t0 = dt.datetime.strptime(t0_str, "%Y-%m-%d")
    tf = (t0 + relativedelta(years=5)) if tf_str is None else dt.datetime.strptime(tf_str, "%Y-%m-%d")

    df = fetch_price_history(ticker_str, t0, tf)

    p_init    = df.iloc[0]["Open"]
    t0_actual = df.index[0]
    shares    = w0 / p_init

    if verbose:
        print(f"[LSI] {t0_actual.date()} — {shares:.6f} parts @ {p_init:.2f}$")

    equity_val = []
    for date, row in df.iterrows():
        if row["Dividends"] > 0 and shares > 0:
            div_cash   = shares * row["Dividends"]
            new_shares = div_cash / row["Close"]
            shares    += new_shares
            if verbose:
                print(f"[LSI][DRIP] {date.date()} — +{new_shares:.6f} parts")

        equity_val.append(shares * row["Close"])

    equity_curve = pd.Series(equity_val, index=df.index)

    p_final   = df.iloc[-1]["Close"]
    tf_actual = df.index[-1]
    w_final   = shares * p_final
    years     = (tf_actual - t0_actual).days / 365.25
    total_ret = (w_final - w0) / w0
    cagr      = (w_final / w0) ** (1 / years) - 1 if years > 0 else np.nan

    metrics = {
        "strategy": "LSI", "ticker": ticker_str,
        "t0": t0_actual.strftime("%Y-%m-%d"), "tf": tf_actual.strftime("%Y-%m-%d"),
        "w0": w0, "w_final": w_final, "shares_final": shares,
        "total_return": total_ret, "cagr": cagr, "years": years,
    }
    return {"metrics": metrics, "equity_curve": equity_curve}


def simulate_dca_drip_fractional(
    ticker_str: str,
    w0: float,
    t0_str: str,
    tf_str: str | None = None,
    freq: str = "M",
    cash_rf_annual: float | None = None,
    verbose: bool = False,
) -> dict:
    """
    Simule la stratégie Dollar-Cost Averaging (DCA) avec DRIP fractionné.

    Logique :
        - w0 est divisé en N tranches égales investies à la fréquence `freq`.
        - Chaque tranche est achetée au prix d'ouverture du jour de bourse aligné.
        - Les dividendes intermédiaires sont réinvestis au prix de clôture (DRIP).
        - Le capital pas encore investi ("cash" en attente) est placé au taux
          sans risque et capitalisé quotidiennement (voir plus bas) au lieu de
          dormir à 0%.

    Rémunération du cash en attente :
        À chaque séance, avant tranche/DRIP du jour, le cash restant est
        capitalisé sur le nombre de jours calendaires (Δj) écoulés depuis la
        séance précédente (donc week-ends/jours fériés inclus, pas seulement
        les jours de bourse) :
            cash_t = cash_{t-1} × (1 + r_annual)^(Δj / 365)
        Cette formule est mathématiquement équivalente à une capitalisation
        jour par jour au taux journalier r_annual^(1/365) - 1 répétée Δj fois
        (composition géométrique), donc "chaque jour où l'argent n'est pas
        encore investi" est bien rémunéré, y compris les jours sans séance.
        r_annual = cash_rf_annual si fourni (taux constant, utile pour les
        tests de sensibilité, ex. 0.0 pour retrouver l'hypothèse initiale du
        papier), sinon le taux du Livret A en vigueur à la date
        (get_livret_a_rate) — taux sans risque le plus cohérent pour du cash
        de particulier français en attente d'investissement.

    Rôle dans le flux global :
        Miroir de simulate_lsi(). Retourne la même structure {metrics, equity_curve}
        pour un traitement symétrique dans run_rolling_window_analysis().

    Returns
    -------
    dict : {'metrics': dict, 'equity_curve': pd.Series}
    """
    FREQ_MAP = {"D": "B", "W": "W-MON", "M": "MS", "Q": "BQS", "S": "6MS", "A": "BYS"}
    if freq.upper() not in FREQ_MAP:
        raise ValueError(f"Fréquence invalide. Choisir parmi : {list(FREQ_MAP.keys())}")

    t0 = dt.datetime.strptime(t0_str, "%Y-%m-%d")
    tf = (t0 + relativedelta(years=5)) if tf_str is None else dt.datetime.strptime(tf_str, "%Y-%m-%d")

    df = fetch_price_history(ticker_str, t0, tf)

    # Alignement des dates théoriques sur jours de bourse réels
    inv_dates_theory = pd.date_range(start=t0, end=tf, freq=FREQ_MAP[freq.upper()])
    actual_inv_dates = set()
    for d in inv_dates_theory:
        available = df.index[df.index >= d]
        if not available.empty:
            actual_inv_dates.add(available[0])
    actual_inv_dates = sorted(actual_inv_dates)

    N = len(actual_inv_dates)
    if N == 0:
        raise ValueError("Calendrier DCA vide : vérifier t0 / tf / fréquence.")
    w_tranche = w0 / N

    if verbose:
        print(f"[DCA] N={N} tranches de {w_tranche:.2f}$ | fréquence={freq.upper()}")

    shares     = 0.0
    cash       = w0    # capital pas encore investi, rémunéré au taux sans risque
    prev_date  = df.index[0]
    equity_val = []

    for date, row in df.iterrows():
        # 1. Capitalisation du cash en attente depuis la séance précédente
        n_days = (date - prev_date).days
        if n_days > 0 and cash > 0:
            r_annual = cash_rf_annual if cash_rf_annual is not None else get_livret_a_rate(date)
            cash *= (1 + r_annual) ** (n_days / 365)
        prev_date = date

        # 2. Tranche du jour, le cas échéant
        if date in actual_inv_dates:
            shares += w_tranche / row["Open"]
            cash   -= w_tranche
            if verbose:
                print(f"[DCA] {date.date()} — +{w_tranche/row['Open']:.6f} parts @ {row['Open']:.2f}$ | cash restant={cash:.2f}$")

        # 3. DRIP
        if row["Dividends"] > 0 and shares > 0:
            div_cash   = shares * row["Dividends"]
            shares    += div_cash / row["Close"]

        equity_val.append(shares * row["Close"] + max(cash, 0.0))

    equity_curve = pd.Series(equity_val, index=df.index)

    t0_actual = df.index[0]
    tf_actual = df.index[-1]
    w_final   = float(equity_curve.iloc[-1])
    years     = (tf_actual - t0_actual).days / 365.25
    total_ret = (w_final - w0) / w0
    cagr      = (w_final / w0) ** (1 / years) - 1 if years > 0 else np.nan

    metrics = {
        "strategy": "DCA", "ticker": ticker_str, "freq": freq.upper(),
        "n_investments": N, "w_tranche": w_tranche,
        "t0": t0_actual.strftime("%Y-%m-%d"), "tf": tf_actual.strftime("%Y-%m-%d"),
        "w0": w0, "w_final": w_final, "shares_final": shares, "cash_final": float(cash),
        "total_return": total_ret, "cagr": cagr, "years": years,
    }
    return {"metrics": metrics, "equity_curve": equity_curve}


# =============================================================================
# COUCHE 2 — Métriques par fenêtre
# =============================================================================

def compute_hpr(equity_curve: pd.Series, w0: float) -> float:
    """
    Calcule le Holding Period Return (HPR) d'une fenêtre.
    HPR = (W_final - W0) / W0

    Rôle : appelée 2×N fois par run_rolling_window_analysis(), une fois par
    (fenêtre × stratégie). Les séries hpr_lsi[] et hpr_dca[] alimentent ensuite
    run_statistical_tests().
    """
    return (float(equity_curve.iloc[-1]) - w0) / w0


def compute_sharpe_sortino(equity_curve: pd.Series, rf_annual: float = 0.02) -> dict:
    """
    Calcule Sharpe et Sortino annualisés depuis une equity curve journalière.

    Méthode :
        r_t        = ln(P_t / P_{t-1})   rendements log journaliers
        excess_r   = r_t - rf/252
        Sharpe     = mean(excess_r) / std(excess_r) × sqrt(252)
        Sortino    = mean(excess_r) / downside_std   × sqrt(252)
        downside_std = std des excess_r négatifs seulement

    Rôle : appelée 2×N fois par run_rolling_window_analysis().
    Retourne nan si trop peu de données (< 5 observations).
    """
    log_r = np.log(equity_curve / equity_curve.shift(1)).dropna()
    if len(log_r) < 5:
        return {"sharpe": np.nan, "sortino": np.nan}

    rf_d      = rf_annual / 252
    exc       = log_r - rf_d
    sharpe    = exc.mean() / exc.std(ddof=1) * np.sqrt(252) if exc.std(ddof=1) > 0 else np.nan

    neg       = exc[exc < 0]
    down_std  = neg.std(ddof=1) if len(neg) > 1 else np.nan
    sortino   = exc.mean() / down_std * np.sqrt(252) if (down_std and down_std > 0) else np.nan

    return {"sharpe": sharpe, "sortino": sortino}


# =============================================================================
# COUCHE 2b — Moteur rolling + agrégation
# =============================================================================

def run_rolling_window_analysis(
    ticker_str   : str,
    w0           : float,
    t0_str       : str,
    window_years : int,
    shift_months : int,
    n_windows    : int,
    dca_freq     : str  = "M",
    rf_annual    : float = 0.02,
    dca_cash_rf  : float | None = None,
    verbose      : bool  = False,
) -> pd.DataFrame:
    """
    Orchestre l'analyse comparative LSI vs DCA sur N fenêtres glissantes.

    Principe :
        Fenêtre i → [t0 + i×shift_months,  t0 + i×shift_months + window_years]
        Chaque fenêtre est indépendante : nouvelle simulation LSI + DCA + métriques.
        Le paramètre shift_months contrôle la granularité du balayage temporel.

    dca_cash_rf : taux (constant) de rémunération du cash DCA en attente. Si
        None (défaut), utilise le barème historique du Livret A par date
        (get_livret_a_rate) — voir simulate_dca_drip_fractional(). Séparé de
        rf_annual, qui reste le taux utilisé comme référence pour Sharpe/Sortino.

    Rôle dans le flux global :
        Cœur de la COUCHE 2b. Appelle les COUCHES 1 et 2 et retourne un DataFrame
        structuré que compute_summary_statistics() et run_statistical_tests()
        consomment directement, et que les fonctions de visualisation (COUCHE 3)
        exploitent pour les graphes.

    Returns
    -------
    pd.DataFrame — colonnes :
        window, t0, tf, market_level_t0,
        lsi_hpr, lsi_cagr, lsi_sharpe, lsi_sortino, lsi_w_final,
        dca_hpr, dca_cagr, dca_sharpe, dca_sortino, dca_w_final,
        hpr_diff  (LSI − DCA)
    """
    t0_base = dt.datetime.strptime(t0_str, "%Y-%m-%d")
    records = []

    for i in range(n_windows):
        t0_i   = t0_base + relativedelta(months=i * shift_months)
        tf_i   = t0_i   + relativedelta(years=window_years)
        t0_i_s = t0_i.strftime("%Y-%m-%d")
        tf_i_s = tf_i.strftime("%Y-%m-%d")

        if verbose:
            print(f"\n[Fenêtre {i+1:02d}/{n_windows}] {t0_i_s} → {tf_i_s}")

        try:
            lsi = simulate_lump_sum_drip_fractional(ticker_str, w0, t0_i_s, tf_i_s, verbose=False)
            dca = simulate_dca_drip_fractional(ticker_str, w0, t0_i_s, tf_i_s, freq=dca_freq, cash_rf_annual=dca_cash_rf, verbose=False)

            lsi_hpr = compute_hpr(lsi["equity_curve"], w0)
            dca_hpr = compute_hpr(dca["equity_curve"], w0)
            lsi_r   = compute_sharpe_sortino(lsi["equity_curve"], rf_annual)
            dca_r   = compute_sharpe_sortino(dca["equity_curve"], rf_annual)

            # Niveau de marché au point d'entrée (prix de clôture normalisé sur la série entière)
            # Utilisé par plot_hpr_diff_vs_market() pour contextualiser les résultats
            market_level = lsi["equity_curve"].iloc[0] / w0  # = 1.0 au départ, sert de référence relative

            records.append({
                "window"          : i + 1,
                "t0"              : t0_i_s,
                "tf"              : tf_i_s,
                "market_level_t0" : lsi["equity_curve"].iloc[0],   # valeur initiale = w0 × prix_relatif
                "lsi_hpr"         : lsi_hpr,
                "lsi_cagr"        : lsi["metrics"]["cagr"],
                "lsi_sharpe"      : lsi_r["sharpe"],
                "lsi_sortino"     : lsi_r["sortino"],
                "lsi_w_final"     : lsi["metrics"]["w_final"],
                "dca_hpr"         : dca_hpr,
                "dca_cagr"        : dca["metrics"]["cagr"],
                "dca_sharpe"      : dca_r["sharpe"],
                "dca_sortino"     : dca_r["sortino"],
                "dca_w_final"     : dca["metrics"]["w_final"],
                "hpr_diff"        : lsi_hpr - dca_hpr,
            })

            if verbose:
                print(f"  LSI: HPR={lsi_hpr*100:.2f}% | Sharpe={lsi_r['sharpe']:.3f} | Sortino={lsi_r['sortino']:.3f}")
                print(f"  DCA: HPR={dca_hpr*100:.2f}% | Sharpe={dca_r['sharpe']:.3f} | Sortino={dca_r['sortino']:.3f}")

        except Exception as e:
            if verbose:
                print(f"  ⚠ Fenêtre {i+1} ignorée : {e}")
            continue

    if not records:
        raise RuntimeError("Aucune fenêtre simulée. Vérifiez les paramètres.")

    df = pd.DataFrame(records)
    df["t0"] = pd.to_datetime(df["t0"])   # converti pour les graphes temporels
    return df


def compute_summary_statistics(df: pd.DataFrame) -> pd.DataFrame:
    """
    Calcule les statistiques descriptives (mean, std, min, median, max) pour
    chaque métrique et chaque stratégie, sur l'ensemble des fenêtres.

    Rôle dans le flux global :
        Première couche de restitution après run_rolling_window_analysis().
        Produit le tableau «macro» affiché par main_comparison() et disponible
        dans output['summary'].

    Returns
    -------
    pd.DataFrame — Index = métriques, colonnes = LSI_*/DCA_*/Diff_mean.
    """
    pairs = [
        ("HPR (%)",     "lsi_hpr",     "dca_hpr",     100),
        ("CAGR (%)",    "lsi_cagr",    "dca_cagr",    100),
        ("Sharpe",      "lsi_sharpe",  "dca_sharpe",  1  ),
        ("Sortino",     "lsi_sortino", "dca_sortino", 1  ),
        ("W_final ($)", "lsi_w_final", "dca_w_final", 1  ),
    ]
    rows = []
    for label, cl, cd, scale in pairs:
        lv = df[cl].dropna() * scale
        dv = df[cd].dropna() * scale
        rows.append({
            "Métrique"  : label,
            "LSI_mean"  : lv.mean(), "LSI_std": lv.std(), "LSI_min": lv.min(),
            "LSI_median": lv.median(), "LSI_max": lv.max(),
            "DCA_mean"  : dv.mean(), "DCA_std": dv.std(), "DCA_min": dv.min(),
            "DCA_median": dv.median(), "DCA_max": dv.max(),
            "Diff_mean" : lv.mean() - dv.mean(),
        })
    return pd.DataFrame(rows).set_index("Métrique")


def run_statistical_tests(df: pd.DataFrame, alpha: float = 0.05) -> pd.DataFrame:
    """
    Teste si LSI et DCA diffèrent statistiquement sur le HPR.

    Tests appliqués (non paramétriques — robustes aux petits échantillons) :
        1. Mann-Whitney U  : compare les rangs des deux distributions (bilatéral
           + unilatéral pour détecter la direction dominante).
        2. Kruskal-Wallis  : généralisation k-groupes (k=2 ici), extensible
           si on veut ajouter d'autres fréquences DCA.
        3. Wilcoxon Signed-Rank pairé : exploite le design pairé — même fenêtre
           = mêmes conditions de marché, donc variance commune annulée.
           C'est le test le plus puissant des trois pour ce design.

    Rôle dans le flux global :
        Dernière couche analytique de main_comparison(). Le résultat est disponible
        dans output['tests'] et peut être incorporé directement dans un article LaTeX.

    Returns
    -------
    pd.DataFrame — colonnes : Statistique, p_value, Significatif, Interprétation.
    """
    lsi = df["lsi_hpr"].dropna().values
    dca = df["dca_hpr"].dropna().values
    common = df[["lsi_hpr","dca_hpr"]].dropna()
    diff   = (common["lsi_hpr"] - common["dca_hpr"]).values

    res = []

    # Mann-Whitney U
    mw_s, mw_p = stats.mannwhitneyu(lsi, dca, alternative="two-sided")
    _, mw_pg   = stats.mannwhitneyu(lsi, dca, alternative="greater")
    sig        = mw_p < alpha
    res.append({
        "Test": "Mann-Whitney U", "Statistique": round(mw_s, 4), "p_value": round(mw_p, 4),
        "Significatif": "✓" if sig else "✗",
        "Interprétation": ("LSI > DCA" if mw_pg < alpha else "DCA > LSI") if sig else "Pas de différence significative",
    })

    # Kruskal-Wallis
    kw_s, kw_p = stats.kruskal(lsi, dca)
    sig = kw_p < alpha
    res.append({
        "Test": "Kruskal-Wallis", "Statistique": round(kw_s, 4), "p_value": round(kw_p, 4),
        "Significatif": "✓" if sig else "✗",
        "Interprétation": "Distributions différentes" if sig else "Pas de différence significative",
    })

    # Wilcoxon Signed-Rank pairé
    if len(diff) >= 10 and not np.all(diff == 0):
        try:
            wx_s, wx_p = stats.wilcoxon(diff, alternative="two-sided")
            sig = wx_p < alpha
            med = np.median(diff)
            res.append({
                "Test": "Wilcoxon Signed-Rank (pairé)", "Statistique": round(wx_s, 4), "p_value": round(wx_p, 4),
                "Significatif": "✓" if sig else "✗",
                "Interprétation": (f"LSI > DCA (Δméd={med*100:+.2f}%)" if med > 0 else f"DCA > LSI (Δméd={med*100:+.2f}%)") if sig else "Différence non significative",
            })
        except Exception:
            pass

    return pd.DataFrame(res).set_index("Test")


# =============================================================================
# COUCHE 3 — Visualisations (lazy : aucune ne s'affiche sans appel explicite)
# =============================================================================

def plot_violin_hpr(df: pd.DataFrame, ticker_str: str = "") -> plt.Figure:
    """
    Violin plot de la distribution des HPR, CAGR, Sharpe et Sortino pour
    LSI (rouge) vs DCA (bleu) sur l'ensemble des fenêtres glissantes.

    Lecture :
        La largeur du violin à chaque valeur est proportionnelle à la densité.
        On voit immédiatement si LSI gagne « souvent mais peu » ou « rarement
        mais beaucoup », et si DCA compresse la dispersion (rôle protecteur).
        Le point blanc = médiane ; la barre noire = IQR.

    Rôle dans le flux global :
        Appelée par main_comparison() qui stocke la figure dans output['plots'].
        Ne s'affiche QUE si on appelle fig.show() ou plt.show() explicitement.

    Returns
    -------
    matplotlib.figure.Figure — stockée dans output['plots']['violin_hpr'].
    """
    metrics = [
        ("HPR (%)",  "lsi_hpr",    "dca_hpr",    100, "Holding Period Return (%)"),
        ("CAGR (%)", "lsi_cagr",   "dca_cagr",   100, "CAGR (%)"),
        ("Sharpe",   "lsi_sharpe", "dca_sharpe",  1,  "Sharpe Ratio"),
        ("Sortino",  "lsi_sortino","dca_sortino",  1,  "Sortino Ratio"),
    ]
    with plt.style.context(_STYLE):
        fig, axes = plt.subplots(1, 4, figsize=(16, 6))
        fig.suptitle(
            f"Distribution des métriques par stratégie — {ticker_str}\n"
            f"({len(df)} fenêtres glissantes)",
            fontsize=13, fontweight="bold", y=1.01
        )

        for ax, (label, cl, cd, scale, ylabel) in zip(axes, metrics):
            data_lsi = df[cl].dropna() * scale
            data_dca = df[cd].dropna() * scale

            # Construire un DataFrame long pour seaborn
            df_long = pd.DataFrame({
                "Valeur"    : pd.concat([data_lsi, data_dca], ignore_index=True),
                "Stratégie" : ["LSI"] * len(data_lsi) + ["DCA"] * len(data_dca),
            })

            sns.violinplot(
                data=df_long, x="Stratégie", y="Valeur",
                palette={"LSI": _CLR_LSI, "DCA": _CLR_DCA},
                inner="box", cut=0, ax=ax
            )
            # Superposer les points individuels (jitter)
            sns.stripplot(
                data=df_long, x="Stratégie", y="Valeur",
                palette={"LSI": _CLR_LSI, "DCA": _CLR_DCA},
                alpha=0.35, size=3, jitter=True, ax=ax
            )
            ax.set_title(label, fontsize=11, fontweight="bold")
            ax.set_ylabel(ylabel, fontsize=9)
            ax.set_xlabel("")
            ax.axhline(0, color="black", linewidth=0.7, linestyle="--", alpha=0.5)

        fig.tight_layout()
    return fig


def plot_scatter_temporal(df: pd.DataFrame, ticker_str: str = "") -> plt.Figure:
    """
    Scatter plot du HPR en fonction du point d'entrée t0 pour LSI et DCA.

    Lecture :
        Axe X = date d'entrée t0 de chaque fenêtre glissante.
        Axe Y = HPR réalisé sur la fenêtre.
        Permet de voir QUAND une stratégie domine l'autre :
        - LSI surperforme si t0 tombe en bas de cycle (entry timing favorable).
        - DCA lisse les entrées sur marché haussier (HPR plus régulier).
        La zone entre les deux courbes est remplie pour visualiser l'avantage relatif.

    Returns
    -------
    matplotlib.figure.Figure — stockée dans output['plots']['scatter_temporal'].
    """
    with plt.style.context(_STYLE):
        fig, ax = plt.subplots(figsize=(14, 6))

        t0_dates = df["t0"]
        lsi_hpr  = df["lsi_hpr"] * 100
        dca_hpr  = df["dca_hpr"] * 100

        ax.plot(t0_dates, lsi_hpr, color=_CLR_LSI, linewidth=2.3, label="LSI", zorder=3)
        ax.plot(t0_dates, dca_hpr, color=_CLR_DCA, linewidth=2.3, label="DCA", zorder=3)
        ax.scatter(t0_dates, lsi_hpr, color=_CLR_LSI, s=40, alpha=0.6, zorder=4)
        ax.scatter(t0_dates, dca_hpr, color=_CLR_DCA, s=40, alpha=0.6, zorder=4)

        # Zone colorée : rouge si LSI > DCA, bleue sinon
        ax.fill_between(t0_dates, lsi_hpr, dca_hpr,
                        where=(lsi_hpr >= dca_hpr), alpha=0.15, color=_CLR_LSI, label="LSI > DCA")
        ax.fill_between(t0_dates, lsi_hpr, dca_hpr,
                        where=(lsi_hpr < dca_hpr),  alpha=0.15, color=_CLR_DCA, label="DCA > LSI")

        ax.axhline(0, color="black", linewidth=2.2, linestyle="--", alpha=0.5)
        ax.set_title(
            f"HPR according to the entry point t0 — {ticker_str}",
            fontsize=12, fontweight="bold"
        )
        ax.set_xlabel("Entry date (t0)", fontsize=14)
        ax.set_ylabel("Holding Period Return (%)", fontsize=14)

        # --- MODIFICATION : Chiffres sur les axes (graduations) plus gros (labelsize=13) ---
        ax.tick_params(axis='both', which='major', labelsize=13)

        # --- MODIFICATION : Légende plus grosse (fontsize de 9 à 13) ---
        ax.legend(fontsize=13, loc="upper right", frameon=True)

        fig.tight_layout()
    return fig


def plot_hpr_diff_vs_market(df: pd.DataFrame, ticker_str: str = "") -> plt.Figure:
    """
    Scatter plot de (HPR_LSI − HPR_DCA) en fonction du niveau de marché à t0.

    Lecture :
        Axe X = valeur initiale du portefeuille LSI à t0 (proxy du niveau de marché).
        Axe Y = différentiel HPR (positif → LSI gagne, négatif → DCA gagne).
        Une corrélation négative confirmerait la thèse : LSI surperforme davantage
        quand on entre BAS (marché déprimé), DCA protège quand on entre HAUT.
        La droite de régression + bande de confiance 95% sont ajoutées.

    C'est le graphe le plus original pour un papier académique : il quantifie
    la sensibilité du différentiel au timing d'entrée.

    Returns
    -------
    matplotlib.figure.Figure — stockée dans output['plots']['hpr_diff_vs_market'].
    """
    with plt.style.context(_STYLE):
        fig, ax = plt.subplots(figsize=(10, 6))

        x = df["market_level_t0"].values
        y = df["hpr_diff"].values * 100

        # Régression linéaire
        mask  = ~(np.isnan(x) | np.isnan(y))
        slope, intercept, r_val, p_val, _ = stats.linregress(x[mask], y[mask])
        x_line = np.linspace(x[mask].min(), x[mask].max(), 200)
        y_line = slope * x_line + intercept

        # Points colorés selon signe
        colors = [_CLR_LSI if v > 0 else _CLR_DCA for v in y]
        ax.scatter(x, y, c=colors, s=50, alpha=0.7, zorder=3, edgecolors="white", linewidths=0.5)

        # Droite de régression
        ax.plot(x_line, y_line, color=_CLR_DIFF, linewidth=2,
                label=f"Régression (R²={r_val**2:.3f}, p={p_val:.3f})")

        ax.axhline(0, color="black", linewidth=0.8, linestyle="--", alpha=0.5)
        ax.set_title(
            f"Différentiel HPR (LSI − DCA) vs niveau de marché à t0 — {ticker_str}",
            fontsize=12, fontweight="bold"
        )
        ax.set_xlabel("Niveau de marché à l'entrée (valeur initiale portefeuille)", fontsize=10)
        ax.set_ylabel("HPR_LSI − HPR_DCA (%)", fontsize=10)

        # Annotations quadrants
        ax.text(0.02, 0.97, "● LSI > DCA", transform=ax.transAxes,
                color=_CLR_LSI, fontsize=8, va="top")
        ax.text(0.02, 0.91, "● DCA > LSI", transform=ax.transAxes,
                color=_CLR_DCA, fontsize=8, va="top")
        ax.legend(fontsize=9)
        fig.tight_layout()
    return fig


def plot_sharpe_temporal(df: pd.DataFrame, ticker_str: str = "") -> plt.Figure:
    """
    Évolution du Sharpe Ratio et du Sortino Ratio selon le point d'entrée t0.

    Lecture :
        Complète plot_scatter_temporal() sur la dimension risk-adjusted.
        DCA devrait avoir un Sharpe plus STABLE (variance cross-fenêtres réduite)
        même si son niveau moyen est plus bas — c'est l'argument quantitatif
        du bénéfice comportemental du DCA (Kahneman-Tversky 1979).
        Les bandes grises montrent ±1 écart-type glissant (fenêtre 5 obs).

    Returns
    -------
    matplotlib.figure.Figure — stockée dans output['plots']['sharpe_temporal'].
    """
    with plt.style.context(_STYLE):
        fig, axes = plt.subplots(2, 1, figsize=(14, 8), sharex=True)
        t0 = df["t0"]

        for ax, (col_lsi, col_dca, title, ylabel) in zip(axes, [
            ("lsi_sharpe", "dca_sharpe", "Sharpe Ratio", "Sharpe"),
            ("lsi_sortino","dca_sortino","Sortino Ratio", "Sortino"),
        ]):
            lsi_v = df[col_lsi]
            dca_v = df[col_dca]

            ax.plot(t0, lsi_v, color=_CLR_LSI, linewidth=1.8, label="LSI")
            ax.plot(t0, dca_v, color=_CLR_DCA, linewidth=1.8, label="DCA")

            # Bandes ±1σ (rolling 5)
            roll_lsi = lsi_v.rolling(5, min_periods=2)
            roll_dca = dca_v.rolling(5, min_periods=2)
            ax.fill_between(t0,
                (roll_lsi.mean() - roll_lsi.std()).values,
                (roll_lsi.mean() + roll_lsi.std()).values,
                alpha=0.10, color=_CLR_LSI)
            ax.fill_between(t0,
                (roll_dca.mean() - roll_dca.std()).values,
                (roll_dca.mean() + roll_dca.std()).values,
                alpha=0.10, color=_CLR_DCA)

            ax.axhline(0, color="black", linewidth=0.8, linestyle="--", alpha=0.5)
            ax.set_title(title, fontsize=11, fontweight="bold")
            ax.set_ylabel(ylabel, fontsize=9)
            ax.legend(fontsize=9)

        axes[-1].set_xlabel("Date d'entrée (t0)", fontsize=10)
        fig.suptitle(
            f"Ratios risk-adjusted selon le point d'entrée — {ticker_str}",
            fontsize=12, fontweight="bold"
        )
        fig.tight_layout()
    return fig


def plot_win_rate_bar(df: pd.DataFrame, ticker_str: str = "") -> plt.Figure:
    """
    Graphe en barres du taux de victoire de LSI vs DCA pour chaque métrique.

    Lecture :
        Pour chaque métrique (HPR, CAGR, Sharpe, Sortino), affiche le pourcentage
        de fenêtres où LSI > DCA (rouge) et où DCA > LSI (bleu).
        Un coup d'œil suffit pour savoir quelle stratégie domine et sur quel plan :
        LSI peut gagner en HPR moyen mais perdre en Sharpe (moins de volatilité DCA).

    Returns
    -------
    matplotlib.figure.Figure — stockée dans output['plots']['win_rate_bar'].
    """
    metrics = [
        ("HPR",    "lsi_hpr",    "dca_hpr"   ),
        ("CAGR",   "lsi_cagr",   "dca_cagr"  ),
        ("Sharpe", "lsi_sharpe", "dca_sharpe" ),
        ("Sortino","lsi_sortino","dca_sortino"),
    ]
    labels, lsi_rates, dca_rates = [], [], []
    for label, cl, cd in metrics:
        sub = df[[cl, cd]].dropna()
        n   = len(sub)
        if n == 0:
            continue
        lsi_w = (sub[cl] > sub[cd]).sum() / n * 100
        labels.append(label)
        lsi_rates.append(lsi_w)
        dca_rates.append(100 - lsi_w)

    x = np.arange(len(labels))
    w = 0.35

    with plt.style.context(_STYLE):
        fig, ax = plt.subplots(figsize=(9, 5))
        bars_lsi = ax.bar(x - w/2, lsi_rates, w, label="LSI > DCA", color=_CLR_LSI, alpha=0.85)
        bars_dca = ax.bar(x + w/2, dca_rates, w, label="DCA > LSI", color=_CLR_DCA, alpha=0.85)

        for bar in bars_lsi:
            ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1,
                    f"{bar.get_height():.0f}%", ha="center", va="bottom", fontsize=9)
        for bar in bars_dca:
            ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1,
                    f"{bar.get_height():.0f}%", ha="center", va="bottom", fontsize=9)

        ax.axhline(50, color="black", linewidth=0.8, linestyle="--", alpha=0.5)
        ax.set_xticks(x)
        ax.set_xticklabels(labels, fontsize=10)
        ax.set_ylabel("% des fenêtres", fontsize=10)
        ax.set_ylim(0, 115)
        ax.set_title(
            f"Taux de victoire par métrique — {ticker_str}\n({len(df)} fenêtres glissantes)",
            fontsize=12, fontweight="bold"
        )
        ax.legend(fontsize=9)
        fig.tight_layout()
    return fig


def plot_hpr_diff_distribution(df: pd.DataFrame, ticker_str: str = "") -> plt.Figure:
    """
    Distribution du différentiel HPR_LSI − HPR_DCA (histogramme + KDE).

    Lecture :
        Si la distribution est centrée à droite de 0, LSI domine systématiquement.
        La queue gauche indique les situations où DCA protège le capital (entrées
        en haut de marché). L'aire rouge = % de fenêtres LSI > DCA.
        La ligne verticale rouge = médiane du différentiel.

    Utile pour la section résultats d'un article : une figure montre immédiatement
    si la supériorité de LSI est robuste ou limitée à certaines conditions.

    Returns
    -------
    matplotlib.figure.Figure — stockée dans output['plots']['hpr_diff_distribution'].
    """
    diff = (df["hpr_diff"] * 100).dropna()

    with plt.style.context(_STYLE):
        fig, ax = plt.subplots(figsize=(10, 5))

        # Histogramme
        ax.hist(diff, bins=max(10, len(diff)//3), color=_CLR_DIFF, alpha=0.4,
                edgecolor="white", linewidth=0.5, density=True, label="Histogram")

        # KDE
        kde_x = np.linspace(diff.min() - 2, diff.max() + 2, 300)
        kde   = stats.gaussian_kde(diff)(kde_x)
        ax.plot(kde_x, kde, color=_CLR_DIFF, linewidth=2, label="KDE")

        # Remplissage des zones
        ax.fill_between(kde_x, kde, where=(kde_x >= 0), alpha=0.15, color=_CLR_LSI, label="LSI > DCA")
        ax.fill_between(kde_x, kde, where=(kde_x < 0),  alpha=0.15, color=_CLR_DCA, label="DCA > LSI")

        # Médiane
        med = diff.median()
        ax.axvline(med, color=_CLR_DIFF, linewidth=1.8, linestyle="--",
                   label=f"Meedian = {med:+.2f}%")
        ax.axvline(0, color="black", linewidth=0.8, linestyle="-", alpha=0.5)

        pct_lsi_wins = (diff > 0).mean() * 100
        ax.set_title(
            f"Distribution of the HPR differential (LSI − DCA) — {ticker_str}\n"
            f"LSI win on {pct_lsi_wins:.1f}% of windows",
            fontsize=12, fontweight="bold"
        )
        ax.set_xlabel("HPR_LSI − HPR_DCA (%)", fontsize=10)
        ax.set_ylabel("Density", fontsize=10)
        ax.legend(fontsize=9)
        fig.tight_layout()
    return fig


# =============================================================================
# COUCHE 3b — Tableaux analytiques supplémentaires
# =============================================================================

def table_top_bottom_windows(df: pd.DataFrame, n: int = 5) -> dict:
    """
    Retourne les N meilleures et N pires fenêtres pour LSI et DCA selon le HPR_diff.

    Lecture :
        Le top-N montre dans quelles conditions de marché LSI surperforme le plus
        (souvent : entrée en bas de cycle, marché baissier précédant une reprise).
        Le bottom-N montre quand DCA protège le plus (entrée haute, marché volatile).

    Rôle dans le flux global :
        Appelée par main_comparison(). Résultat stocké dans output['tables']['top_bottom'].
        Peut être converti en LaTeX via df.to_latex() directement.

    Returns
    -------
    dict : {'top': pd.DataFrame, 'bottom': pd.DataFrame}
    """
    cols = ["window", "t0", "tf", "lsi_hpr", "dca_hpr", "hpr_diff",
            "lsi_sharpe", "dca_sharpe", "lsi_cagr", "dca_cagr"]
    sub  = df[cols].copy()
    sub["lsi_hpr"]   *= 100
    sub["dca_hpr"]   *= 100
    sub["hpr_diff"]  *= 100
    sub["lsi_cagr"]  *= 100
    sub["dca_cagr"]  *= 100

    top    = sub.nlargest(n,  "hpr_diff").reset_index(drop=True)
    bottom = sub.nsmallest(n, "hpr_diff").reset_index(drop=True)

    return {"top": top, "bottom": bottom}


def table_regime_breakdown(df: pd.DataFrame) -> pd.DataFrame:
    """
    Décompose les résultats selon le régime de marché à t0.

    Méthode :
        Le niveau de marché à t0 (market_level_t0) est discrétisé en tertiles :
            - Tertile bas  (T1) : entrée en marché déprimé
            - Tertile moyen(T2) : entrée en marché neutre
            - Tertile haut (T3) : entrée en marché élevé
        Pour chaque tertile, on calcule :
            - HPR moyen LSI vs DCA
            - % fenêtres où LSI > DCA
            - Différentiel médian

    Lecture :
        Si T1 → HPR_diff > 0 et T3 → HPR_diff < 0, on confirme empiriquement
        que LSI est sensible au timing et DCA est la meilleure stratégie pour
        un investisseur ne pouvant pas identifier les bas de cycle.

    Returns
    -------
    pd.DataFrame — stocké dans output['tables']['regime_breakdown'].
    """
    df = df.copy()
    df["regime"] = pd.qcut(
        df["market_level_t0"], q=3,
        labels=["T1 — Marché bas", "T2 — Neutre", "T3 — Marché haut"]
    )

    rows = []
    for regime, grp in df.groupby("regime", observed=True):
        n = len(grp)
        rows.append({
            "Régime"               : regime,
            "N fenêtres"           : n,
            "HPR_LSI moyen (%)"    : grp["lsi_hpr"].mean() * 100,
            "HPR_DCA moyen (%)"    : grp["dca_hpr"].mean() * 100,
            "Diff médiane (%)"     : grp["hpr_diff"].median() * 100,
            "LSI gagne (%)"        : (grp["hpr_diff"] > 0).mean() * 100,
            "Sharpe LSI moyen"     : grp["lsi_sharpe"].mean(),
            "Sharpe DCA moyen"     : grp["dca_sharpe"].mean(),
        })
    return pd.DataFrame(rows).set_index("Régime")


# =============================================================================
# COUCHE 4 — Programme principal
# =============================================================================

def main_comparison(
    ticker_str   : str,
    w0           : float,
    t0_str       : str,
    window_years : int   = 3,
    shift_months : int   = 1,
    n_windows    : int   = 24,
    dca_freq     : str   = "M",
    rf_annual    : float = 0.02,
    dca_cash_rf  : float | None = None,
    alpha        : float = 0.05,
    verbose      : bool  = False,
) -> dict:
    """
    Point d'entrée principal — Analyse comparative LSI vs DCA par fenêtre glissante.

    Flux d'exécution :
        1. run_rolling_window_analysis()  → df_results
        2. compute_summary_statistics()   → df_summary
        3. run_statistical_tests()        → df_tests
        4. table_top_bottom_windows()     → tables top/bottom N fenêtres
        5. table_regime_breakdown()       → stats par régime de marché
        6. Construction des figures (lazy — non affichées) :
             plot_violin_hpr()            → fig_violin
             plot_scatter_temporal()      → fig_scatter
             plot_hpr_diff_vs_market()    → fig_diff_vs_mkt
             plot_sharpe_temporal()       → fig_sharpe
             plot_win_rate_bar()          → fig_winrate
             plot_hpr_diff_distribution() → fig_diff_dist

    Paramètres
    ----------
    ticker_str   : str    Symbole boursier (ex: '^FCHI' pour CAC 40).
    w0           : float  Capital total par simulation.
    t0_str       : str    Premier point d'entrée 'YYYY-MM-DD'.
    window_years : int    Durée de chaque fenêtre (années).
    shift_months : int    Décalage entre deux fenêtres consécutives (mois).
    n_windows    : int    Nombre de fenêtres à simuler.
    dca_freq     : str    Fréquence DCA ('D','W','M','Q','S','A').
    rf_annual    : float  Taux sans risque annualisé (Sharpe/Sortino).
    dca_cash_rf  : float | None  Taux de rémunération du cash DCA en attente.
        None (défaut) → barème historique du Livret A par date. Un float
        fixe ce taux constant (ex: 0.0 pour l'ancienne hypothèse "cash à 0%").
    alpha        : float  Seuil de significativité des tests stat.
    verbose      : bool   Affichage détaillé fenêtre par fenêtre.

    Returns
    -------
    dict :
        'results'  → pd.DataFrame  résultats bruts N fenêtres
        'summary'  → pd.DataFrame  statistiques descriptives
        'tests'    → pd.DataFrame  résultats des 3 tests statistiques
        'tables'   → dict
            'top_bottom'       → {'top': df, 'bottom': df}
            'regime_breakdown' → pd.DataFrame
        'plots'    → dict (figures NON affichées — appeler .show() pour afficher)
            'violin_hpr'            → fig
            'scatter_temporal'      → fig
            'hpr_diff_vs_market'    → fig
            'sharpe_temporal'       → fig
            'win_rate_bar'          → fig
            'hpr_diff_distribution' → fig
    """
    print("=" * 70)
    print("  ANALYSE COMPARATIVE  LSI  vs  DCA — Fenêtres Glissantes")
    print("=" * 70)
    print(f"  Ticker        : {ticker_str}")
    print(f"  Capital w0    : {w0:,.0f}$")
    print(f"  Premier t0    : {t0_str}")
    print(f"  Fenêtre       : {window_years} an(s)  |  Décalage : {shift_months} mois")
    print(f"  Nb fenêtres   : {n_windows}  |  Fréq. DCA : {dca_freq.upper()}")
    print(f"  Rf annuel     : {rf_annual*100:.1f}%  |  α = {alpha}")
    cash_rf_label = f"{dca_cash_rf*100:.2f}% (constant)" if dca_cash_rf is not None else "barème Livret A (historique)"
    print(f"  Rémun. cash DCA : {cash_rf_label}")
    print("=" * 70)

    # --- ÉTAPE 1 : Simulations rolling ---
    print("\n[1/5] Simulation des fenêtres glissantes...")
    df_results = run_rolling_window_analysis(
        ticker_str=ticker_str, w0=w0, t0_str=t0_str,
        window_years=window_years, shift_months=shift_months,
        n_windows=n_windows, dca_freq=dca_freq, rf_annual=rf_annual,
        dca_cash_rf=dca_cash_rf, verbose=verbose,
    )
    print(f"  ✓ {len(df_results)} fenêtres simulées.")

    # --- ÉTAPE 2 : Statistiques descriptives ---
    print("\n[2/5] Statistiques synthétiques...")
    df_summary = compute_summary_statistics(df_results)
    pd.set_option("display.float_format", "{:.4f}".format)
    pd.set_option("display.max_columns", None)
    pd.set_option("display.width", 120)
    print("\n" + "─" * 70)
    print("  STATISTIQUES DESCRIPTIVES")
    print("─" * 70)
    print(df_summary.to_string())
    lsi_wins = (df_results["hpr_diff"] > 0).sum()
    print(f"\n  LSI > DCA dans {lsi_wins}/{len(df_results)} fenêtres ({lsi_wins/len(df_results)*100:.1f}%)")

    # --- ÉTAPE 3 : Tests statistiques ---
    print("\n[3/5] Tests statistiques...")
    df_tests = run_statistical_tests(df_results, alpha=alpha)
    print("\n" + "─" * 70)
    print(f"  TESTS STATISTIQUES  (H0 : HPR_LSI = HPR_DCA  |  α={alpha})")
    print("─" * 70)
    print(df_tests.to_string())

    # --- ÉTAPE 4 : Tableaux analytiques ---
    print("\n[4/5] Construction des tableaux analytiques...")
    tb   = table_top_bottom_windows(df_results, n=5)
    reg  = table_regime_breakdown(df_results)
    print("\n  Top 5 fenêtres (LSI domine le plus) :")
    print(tb["top"].to_string(index=False))
    print("\n  Bottom 5 fenêtres (DCA domine le plus) :")
    print(tb["bottom"].to_string(index=False))
    print("\n  Breakdown par régime de marché :")
    print(reg.to_string())

    # --- ÉTAPE 5 : Construction des figures (lazy) ---
    print("\n[5/5] Préparation des graphes (non affichés)...")
    matplotlib.use("Agg")   # backend non-interactif pendant la construction

    plots = {
        "violin_hpr"            : plot_violin_hpr(df_results, ticker_str),
        "scatter_temporal"      : plot_scatter_temporal(df_results, ticker_str),
        "hpr_diff_vs_market"    : plot_hpr_diff_vs_market(df_results, ticker_str),
        "sharpe_temporal"       : plot_sharpe_temporal(df_results, ticker_str),
        "win_rate_bar"          : plot_win_rate_bar(df_results, ticker_str),
        "hpr_diff_distribution" : plot_hpr_diff_distribution(df_results, ticker_str),
    }
    plt.close("all")   # libère la mémoire, les objets Figure restent accessibles

    print("  ✓ Graphes disponibles :")
    for k in plots:
        print(f"      output['plots']['{k}'].show()")

    print("\n" + "=" * 70)
    print("  DONE")
    print("=" * 70)

    return {
        "results" : df_results,
        "summary" : df_summary,
        "tests"   : df_tests,
        "tables"  : {"top_bottom": tb, "regime_breakdown": reg},
        "plots"   : plots,
    }

# =============================================================================
# EXEMPLE D'UTILISATION
# =============================================================================

if __name__ == "__main__":

    output = main_comparison(
        ticker_str   = "^FCHI",       # CAC 40
        w0           = 12_000,
        t0_str       = "2010-01-04",
        window_years = 5,
        shift_months = 1,             # ← paramètre clé : granularité du balayage
        n_windows    = 60,
        dca_freq     = "M",
        rf_annual    = 0.02,
        alpha        = 0.05,
        verbose      = False,
    )

    # --- Accès aux résultats ---
    df_results = output["results"]          # DataFrame brut N×métriques
    df_tests   = output["tests"]            # tests stat
    top5       = output["tables"]["top_bottom"]["top"]
    regime     = output["tables"]["regime_breakdown"]

import datetime as dt
import matplotlib.pyplot as plt
import yfinance as yf

# 1. Date Configuration and Data Fetching
ticker_str = "^FCHI"  # CAC 40 Index Ticker
start_date = "2010-01-04"
end_date = "2020-01-01"

# Download historical daily data
df = yf.Ticker(ticker_str).history(start=start_date, end=end_date)
if df.index.tz is not None:
    df.index = df.index.tz_localize(None)

# 2. Resample to Monthly Start Frequency ("MS")
# Extracts the first available "Open" price for each chronological month
df_monthly_open = df["Open"].resample("MS").first()

# 3. Chart Generation
plt.style.use("seaborn-v0_8-whitegrid")
fig, ax = plt.subplots(figsize=(12, 6))

# Main line plot mapping the evolution of monthly entry prices
ax.plot(
    df_monthly_open.index,
    df_monthly_open.values,
    color="#457B9D",
    linewidth=2,
    label="Monthly Opening Price (P_open)",
)

# Scatter plot highlighting individual systematic DCA purchase points
ax.scatter(
    df_monthly_open.index,
    df_monthly_open.values,
    color="#E63946",
    s=25,
    zorder=3,
    label="DCA Tranche Purchases (Monthly)",
)

# Visual Formatting
ax.set_title(
    "Evolution of CAC 40 Opening Entry Points (2010 — 2020)\nThe Impact of the Upward Market Drift on DCA Cost Averaging",
    fontsize=12,
    fontweight="bold",
    pad=15,
)
ax.set_xlabel("Years", fontsize=10)
ax.set_ylabel("Opening Price ($P_{\\text{open}}$)", fontsize=10)
ax.legend(loc="upper left", fontsize=9)

# Layout Optimization
fig.tight_layout()

# Save high-resolution figure for LaTeX compilation
plt.savefig("cac40_monthly_open.png", dpi=300)
plt.show()

# ── Paramètres communs ───────────────────────────────────────────
COMMON = dict(
    w0           = 10_000,
    t0_str       = "2010-01-04",
    window_years = 5,
    shift_months = 1,
    n_windows    = 60,      # jan 2010 → jan 2015 : 60 fenêtres, dernière tf = jan 2020
    dca_freq     = "M",
    rf_annual    = 0.02,
    alpha        = 0.05,
    verbose      = False,
)

# ── CAC 40 — indice ──────────────────────────────────────────────
output_cac = main_comparison(ticker_str="^FCHI", **COMMON)

# ── Constituants du CAC 40 ───────────────────────────────────────
CAC40_TICKERS = {
    "Air Liquide"        : "AI.PA",
    "Airbus"             : "AIR.PA",
    "ArcelorMittal"      : "MT.PA",
    "AXA"                : "CS.PA",
    "BNP Paribas"        : "BNP.PA",
    "Bouygues"           : "EN.PA",
    "Capgemini"          : "CAP.PA",
    "Carrefour"          : "CA.PA",
    "Crédit Agricole"    : "ACA.PA",
    "Danone"             : "BN.PA",
    "Dassault Systèmes"  : "DSY.PA",
    "Engie"              : "ENGI.PA",
    "EssilorLuxottica"   : "EL.PA",
    "Hermès"             : "RMS.PA",
    "Kering"             : "KER.PA",
    "Legrand"            : "LR.PA",
    "L'Oréal"            : "OR.PA",
    "LVMH"               : "MC.PA",
    "Michelin"           : "ML.PA",
    "Orange"             : "ORA.PA",
    "Pernod Ricard"      : "RI.PA",
    "Publicis"           : "PUB.PA",
    "Renault"            : "RNO.PA",
    "Safran"             : "SAF.PA",
    "Saint-Gobain"       : "SGO.PA",
    "Sanofi"             : "SAN.PA",
    "Schneider Electric" : "SU.PA",
    "Société Générale"   : "GLE.PA",
    "Stellantis"         : "STLAM.MI",  # coté Milan
    "STMicroelectronics" : "STM.PA",
    "Teleperformance"    : "TEP.PA",
    "Thales"             : "HO.PA",
    "TotalEnergies"      : "TTE.PA",
    "Unibail-Rodamco"    : "URW.PA",
    "Veolia"             : "VIE.PA",
    "Vinci"              : "DG.PA",
    "Vivendi"            : "VIV.PA",
    "Worldline"          : "WLN.PA",
    "Accor"              : "AC.PA",
    "Eurofins"           : "ERF.PA",
}

# ── Boucle sur tous les constituants ────────────────────────────
results_all = {}

for name, ticker in CAC40_TICKERS.items():
    print(f"\n{'='*60}")
    print(f"  {name}  ({ticker})")
    print(f"{'='*60}")
    try:
        results_all[name] = main_comparison(ticker_str=ticker, **COMMON)
    except Exception as e:
        print(f"  ⚠  {name} ignoré : {e}")
        results_all[name] = None

# ── Accès aux résultats ──────────────────────────────────────────
# Indice
df_cac_results = output_cac["results"]
df_cac_summary = output_cac["summary"]

# Un constituant en particulier
lvmh = results_all["LVMH"]
if lvmh:
    lvmh["summary"]
    lvmh["plots"]["violin_hpr"].show()

# Comparer les HPR médians de tous les titres
import pandas as pd
summary_cross = pd.DataFrame({
    name : res["summary"]["LSI_median"] if res else None
    for name, res in results_all.items()
}).T
print(summary_cross)

# =============================================================================
# TABLEAU COMPARATIF  LSI  vs  DCA  (fréquences M / 6M / A)
# =============================================================================

FREQ_CONFIGS = [
    ("M",  "DCA mensuel  (12×/an)"),
    ("S",  "DCA semestriel (2×/an)"),
    ("A",  "DCA annuel    (1×/an)"),
]

COMMON = dict(
    ticker_str   = "^FCHI",
    w0           = 12_000,
    t0_str       = "2010-01-04",
    window_years = 5,
    shift_months = 1,
    n_windows    = 60,
    rf_annual    = 0.02,
    alpha        = 0.05,
    verbose      = False,
)

# ── 1. Collecte des résultats ────────────────────────────────────
runs = {}
for freq, label in FREQ_CONFIGS:
    print(f"\n>>> {label}")
    runs[freq] = main_comparison(**COMMON, dca_freq=freq)

# ── 2. Construction du tableau ───────────────────────────────────
METRICS = [
    ("HPR (%)",     "lsi_hpr",     "dca_hpr",     100),
    ("CAGR (%)",    "lsi_cagr",    "dca_cagr",    100),
    ("Sharpe",      "lsi_sharpe",  "dca_sharpe",    1),
    ("Sortino",     "lsi_sortino", "dca_sortino",   1),
    ("W_final (€)", "lsi_w_final", "dca_w_final",   1),
]

rows = []
for freq, label in FREQ_CONFIGS:
    df = runs[freq]["results"]
    for metric_label, col_lsi, col_dca, scale in METRICS:
        lsi_v = df[col_lsi].dropna() * scale
        dca_v = df[col_dca].dropna() * scale
        rows.append({
            "Fréquence DCA" : label,
            "Métrique"      : metric_label,
            "LSI mean"      : lsi_v.mean(),
            "LSI std"       : lsi_v.std(),
            "LSI median"    : lsi_v.median(),
            "DCA mean"      : dca_v.mean(),
            "DCA std"       : dca_v.std(),
            "DCA median"    : dca_v.median(),
            "Δ mean (LSI−DCA)" : lsi_v.mean() - dca_v.mean(),
            "LSI wins (%)"  : (df[col_lsi] > df[col_dca]).mean() * 100,
        })

import pandas as pd
table = (
    pd.DataFrame(rows)
    .set_index(["Fréquence DCA", "Métrique"])
)

# ── 3. Affichage console ─────────────────────────────────────────
pd.set_option("display.float_format", "{:,.3f}".format)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 140)
print("\n")
print(table.to_string())

# ── 4. Export LaTeX ──────────────────────────────────────────────
latex = (
    table
    .style
    .format({
        "LSI mean"         : "{:.2f}",
        "LSI std"          : "{:.2f}",
        "LSI median"       : "{:.2f}",
        "DCA mean"         : "{:.2f}",
        "DCA std"          : "{:.2f}",
        "DCA median"       : "{:.2f}",
        "Δ mean (LSI−DCA)" : "{:+.2f}",
        "LSI wins (%)"     : "{:.1f}",
    })
    .to_latex(
        caption  = "Comparative statistics — LSI vs DCA at three rebalancing "
                   "frequencies. CAC\\,40 (\\textasciicircum FCHI), "
                   "$W_0 = \\EUR{12{,}000}$, rolling windows 2010--2015 "
                   "($N=60$, $\\Delta t = 5$\\,years, shift $= 1$\\,month).",
        label    = "tab:lsi_dca_freq",
        hrules   = True,
        position = "htbp",
    )
)
with open("table_lsi_dca.tex", "w") as f:
    f.write(latex)
print("\nTableau LaTeX sauvegardé → table_lsi_dca.tex")

# =============================================================================
# TABLEAU COMPARATIF  LSI  vs  DCA  (fréquences M / 6M / A)
# =============================================================================

FREQ_CONFIGS = [
    ("M",  "DCA mensuel  (12×/an)"),
    ("S",  "DCA semestriel (2×/an)"),
    ("A",  "DCA annuel    (1×/an)"),
]

COMMON = dict(
    ticker_str   = "^FCHI",
    w0           = 12_000,
    t0_str       = "2010-01-04",
    window_years = 5,
    shift_months = 1,
    n_windows    = 60,
    rf_annual    = 0.02,
    alpha        = 0.05,
    verbose      = False,
)

# ── 1. Collecte des résultats ────────────────────────────────────
runs = {}
for freq, label in FREQ_CONFIGS:
    print(f"\n>>> {label}")
    runs[freq] = main_comparison(**COMMON, dca_freq=freq)

# ── 2. Construction du tableau ───────────────────────────────────
METRICS = [
    ("HPR (%)",     "lsi_hpr",     "dca_hpr",     100),
    ("CAGR (%)",    "lsi_cagr",    "dca_cagr",    100),
    ("Sharpe",      "lsi_sharpe",  "dca_sharpe",    1),
    ("Sortino",     "lsi_sortino", "dca_sortino",   1),
    ("W_final (€)", "lsi_w_final", "dca_w_final",   1),
]

rows = []
for freq, label in FREQ_CONFIGS:
    df = runs[freq]["results"]
    for metric_label, col_lsi, col_dca, scale in METRICS:
        lsi_v = df[col_lsi].dropna() * scale
        dca_v = df[col_dca].dropna() * scale
        rows.append({
            "Fréquence DCA" : label,
            "Métrique"      : metric_label,
            "LSI mean"      : lsi_v.mean(),
            "LSI std"       : lsi_v.std(),
            "LSI median"    : lsi_v.median(),
            "DCA mean"      : dca_v.mean(),
            "DCA std"       : dca_v.std(),
            "DCA median"    : dca_v.median(),
            "Δ mean (LSI−DCA)" : lsi_v.mean() - dca_v.mean(),
            "LSI wins (%)"  : (df[col_lsi] > df[col_dca]).mean() * 100,
        })

import pandas as pd
table = (
    pd.DataFrame(rows)
    .set_index(["Fréquence DCA", "Métrique"])
)

# ── 3. Affichage console ─────────────────────────────────────────
pd.set_option("display.float_format", "{:,.3f}".format)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 140)
print("\n")
print(table.to_string())

# =============================================================================
# TABLEAU COMPARATIF  LSI  vs  DCA  (fréquences M / 6M / A)
# =============================================================================

FREQ_CONFIGS = [
    ("M",  "DCA mensuel  (12×/an)"),
    ("S",  "DCA semestriel (2×/an)"),
    ("A",  "DCA annuel    (1×/an)"),
]

COMMON = dict(
    ticker_str   = "CAP.PA",
    w0           = 12_000,
    t0_str       = "2010-01-04",
    window_years = 5,
    shift_months = 1,
    n_windows    = 60,
    rf_annual    = 0.02,
    alpha        = 0.05,
    verbose      = False,
)

# ── 1. Collecte des résultats ────────────────────────────────────
runs = {}
for freq, label in FREQ_CONFIGS:
    print(f"\n>>> {label}")
    runs[freq] = main_comparison(**COMMON, dca_freq=freq)

# ── 2. Construction du tableau ───────────────────────────────────
METRICS = [
    ("HPR (%)",     "lsi_hpr",     "dca_hpr",     100),
    ("CAGR (%)",    "lsi_cagr",    "dca_cagr",    100),
    ("Sharpe",      "lsi_sharpe",  "dca_sharpe",    1),
    ("Sortino",     "lsi_sortino", "dca_sortino",   1),
    ("W_final (€)", "lsi_w_final", "dca_w_final",   1),
]

rows = []
for freq, label in FREQ_CONFIGS:
    df = runs[freq]["results"]
    for metric_label, col_lsi, col_dca, scale in METRICS:
        lsi_v = df[col_lsi].dropna() * scale
        dca_v = df[col_dca].dropna() * scale
        rows.append({
            "Fréquence DCA" : label,
            "Métrique"      : metric_label,
            "LSI mean"      : lsi_v.mean(),
            "LSI std"       : lsi_v.std(),
            "LSI median"    : lsi_v.median(),
            "DCA mean"      : dca_v.mean(),
            "DCA std"       : dca_v.std(),
            "DCA median"    : dca_v.median(),
            "Δ mean (LSI−DCA)" : lsi_v.mean() - dca_v.mean(),
            "LSI wins (%)"  : (df[col_lsi] > df[col_dca]).mean() * 100,
        })

import pandas as pd
table = (
    pd.DataFrame(rows)
    .set_index(["Fréquence DCA", "Métrique"])
)

# ── 3. Affichage console ─────────────────────────────────────────
pd.set_option("display.float_format", "{:,.3f}".format)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 140)
print("\n")
table

import pandas as pd

def run_backtest_for_ticker(ticker_str: str, **kwargs) -> pd.DataFrame:
    """
    Exécute le backtest multi-fréquence LSI vs DCA pour un ticker donné
    et retourne le tableau comparatif mis en forme.
    """

    FREQ_CONFIGS = [
        ("M",  "DCA mensuel  (12×/an)"),
        ("S",  "DCA semestriel (2×/an)"),
        ("A",  "DCA annuel    (1×/an)"),
    ]

    METRICS = [
        ("HPR (%)",     "lsi_hpr",     "dca_hpr",     100),
        ("CAGR (%)",    "lsi_cagr",    "dca_cagr",    100),
        ("Sharpe",      "lsi_sharpe",  "dca_sharpe",    1),
        ("Sortino",     "lsi_sortino", "dca_sortino",   1),
        ("W_final (€)", "lsi_w_final", "dca_w_final",   1),
    ]

    # Configuration de base par défaut
    COMMON = dict(
        ticker_str   = ticker_str,
        w0           = 12_000,
        t0_str       = "2010-01-04",
        window_years = 5,
        shift_months = 1,
        n_windows    = 60,
        rf_annual    = 0.02,
        alpha        = 0.05,
        verbose      = False,
    )

    # Écrase les paramètres par défaut si tu passes des arguments optionnels (ex: w0=24000)
    COMMON.update(kwargs)

    # ── 1. Collecte des résultats ────────────────────────────────────
    runs = {}
    for freq, label in FREQ_CONFIGS:
        if COMMON.get("verbose"):
            print(f"\n>>> {label} pour {ticker_str}")
        runs[freq] = main_comparison(**COMMON, dca_freq=freq)

    # ── 2. Construction du tableau ───────────────────────────────────
    rows = []
    for freq, label in FREQ_CONFIGS:
        df = runs[freq]["results"]
        for metric_label, col_lsi, col_dca, scale in METRICS:
            lsi_v = df[col_lsi].dropna() * scale
            dca_v = df[col_dca].dropna() * scale

            rows.append({
                "Fréquence DCA" : label,
                "Métrique"      : metric_label,
                "LSI mean"      : lsi_v.mean(),
                "LSI std"       : lsi_v.std(),
                "LSI median"    : lsi_v.median(),
                "DCA mean"      : dca_v.mean(),
                "DCA std"       : dca_v.std(),
                "DCA median"    : dca_v.median(),
                "Δ mean (LSI−DCA)" : lsi_v.mean() - dca_v.mean(),
                "LSI wins (%)"  : (df[col_lsi] > df[col_dca]).mean() * 100,
            })

    table = pd.DataFrame(rows).set_index(["Fréquence DCA", "Métrique"])
    return table

# ── Configuration de l'affichage Pandas ──────────────────────────
pd.set_option("display.float_format", "{:,.3f}".format)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 140)

# Exemple 1 : Utilisation standard avec les valeurs par défaut
df_cap = run_backtest_for_ticker("CAP.PA")
df_cap

# Exemple 1 : Utilisation standard avec les valeurs par défaut
df= run_backtest_for_ticker("ML.PA")
df

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("RNO.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("STLAM.MI")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("SU.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("ACA.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("BNP.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("GLE.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("AI.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("DG.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("ENGI.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("ORA.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("TTE.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("VIE.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("EL.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("SAN.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("ERF.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("AIR.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("ALO.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("HO.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("SAF.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("LR.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("SGO.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("CDI.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("KER.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("MC.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("OR.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("RMS.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("AC.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("BN.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("CA.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("RI.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("EN.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("PUB.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("TEP.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("VIV.PA")

# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("DSY.PA")



# Exemple 1 : Utilisation standard avec les valeurs par défaut
run_backtest_for_ticker("CS.PA")





# =============================================================================
# TABLEAU COMPARATIF  LSI  vs  DCA  (fréquences M / 6M / A)
# =============================================================================

FREQ_CONFIGS = [
    ("M",  "DCA mensuel  (12×/an)"),
    ("S",  "DCA semestriel (2×/an)"),
    ("A",  "DCA annuel    (1×/an)"),
]

COMMON = dict(
    ticker_str   = "ORA.PA",
    w0           = 12_000,
    t0_str       = "2010-01-04",
    window_years = 5,
    shift_months = 1,
    n_windows    = 60,
    rf_annual    = 0.02,
    alpha        = 0.05,
    verbose      = False,
)

# ── 1. Collecte des résultats ────────────────────────────────────
runs = {}
for freq, label in FREQ_CONFIGS:
    print(f"\n>>> {label}")
    runs[freq] = main_comparison(**COMMON, dca_freq=freq)

# ── 2. Construction du tableau ───────────────────────────────────
METRICS = [
    ("HPR (%)",     "lsi_hpr",     "dca_hpr",     100),
    ("CAGR (%)",    "lsi_cagr",    "dca_cagr",    100),
    ("Sharpe",      "lsi_sharpe",  "dca_sharpe",    1),
    ("Sortino",     "lsi_sortino", "dca_sortino",   1),
    ("W_final (€)", "lsi_w_final", "dca_w_final",   1),
]

rows = []
for freq, label in FREQ_CONFIGS:
    df = runs[freq]["results"]
    for metric_label, col_lsi, col_dca, scale in METRICS:
        lsi_v = df[col_lsi].dropna() * scale
        dca_v = df[col_dca].dropna() * scale
        rows.append({
            "Fréquence DCA" : label,
            "Métrique"      : metric_label,
            "LSI mean"      : lsi_v.mean(),
            "LSI std"       : lsi_v.std(),
            "LSI median"    : lsi_v.median(),
            "DCA mean"      : dca_v.mean(),
            "DCA std"       : dca_v.std(),
            "DCA median"    : dca_v.median(),
            "Δ mean (LSI−DCA)" : lsi_v.mean() - dca_v.mean(),
            "LSI wins (%)"  : (df[col_lsi] > df[col_dca]).mean() * 100,
        })

import pandas as pd
table = (
    pd.DataFrame(rows)
    .set_index(["Fréquence DCA", "Métrique"])
)

# ── 3. Affichage console ─────────────────────────────────────────
pd.set_option("display.float_format", "{:,.3f}".format)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 140)
print("\n")
print(table.to_string())

# =============================================================================
# TABLEAU COMPARATIF  LSI  vs  DCA  (fréquences M / 6M / A)
# =============================================================================

FREQ_CONFIGS = [
    ("M",  "DCA mensuel  (12×/an)"),
    ("S",  "DCA semestriel (2×/an)"),
    ("A",  "DCA annuel    (1×/an)"),
]

COMMON = dict(
    ticker_str   = "RI.PA",
    w0           = 12_000,
    t0_str       = "2010-01-04",
    window_years = 5,
    shift_months = 1,
    n_windows    = 60,
    rf_annual    = 0.02,
    alpha        = 0.05,
    verbose      = False,
)

# ── 1. Collecte des résultats ────────────────────────────────────
runs = {}
for freq, label in FREQ_CONFIGS:
    print(f"\n>>> {label}")
    runs[freq] = main_comparison(**COMMON, dca_freq=freq)

# ── 2. Construction du tableau ───────────────────────────────────
METRICS = [
    ("HPR (%)",     "lsi_hpr",     "dca_hpr",     100),
    ("CAGR (%)",    "lsi_cagr",    "dca_cagr",    100),
    ("Sharpe",      "lsi_sharpe",  "dca_sharpe",    1),
    ("Sortino",     "lsi_sortino", "dca_sortino",   1),
    ("W_final (€)", "lsi_w_final", "dca_w_final",   1),
]

rows = []
for freq, label in FREQ_CONFIGS:
    df = runs[freq]["results"]
    for metric_label, col_lsi, col_dca, scale in METRICS:
        lsi_v = df[col_lsi].dropna() * scale
        dca_v = df[col_dca].dropna() * scale
        rows.append({
            "Fréquence DCA" : label,
            "Métrique"      : metric_label,
            "LSI mean"      : lsi_v.mean(),
            "LSI std"       : lsi_v.std(),
            "LSI median"    : lsi_v.median(),
            "DCA mean"      : dca_v.mean(),
            "DCA std"       : dca_v.std(),
            "DCA median"    : dca_v.median(),
            "Δ mean (LSI−DCA)" : lsi_v.mean() - dca_v.mean(),
            "LSI wins (%)"  : (df[col_lsi] > df[col_dca]).mean() * 100,
        })

import pandas as pd
table = (
    pd.DataFrame(rows)
    .set_index(["Fréquence DCA", "Métrique"])
)

# ── 3. Affichage console ─────────────────────────────────────────
pd.set_option("display.float_format", "{:,.3f}".format)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 140)
print("\n")
print(table.to_string())



# =============================================================================
# TABLEAU COMPARATIF  LSI  vs  DCA  (fréquences M / 6M / A)
# =============================================================================

FREQ_CONFIGS = [
    ("M",  "DCA mensuel  (12×/an)"),
    ("S",  "DCA semestriel (2×/an)"),
    ("A",  "DCA annuel    (1×/an)"),
]

COMMON = dict(
    ticker_str   = "CS.PA",
    w0           = 12_000,
    t0_str       = "2010-01-04",
    window_years = 5,
    shift_months = 1,
    n_windows    = 60,
    rf_annual    = 0.02,
    alpha        = 0.05,
    verbose      = False,
)

# ── 1. Collecte des résultats ────────────────────────────────────
runs = {}
for freq, label in FREQ_CONFIGS:
    print(f"\n>>> {label}")
    runs[freq] = main_comparison(**COMMON, dca_freq=freq)

# ── 2. Construction du tableau ───────────────────────────────────
METRICS = [
    ("HPR (%)",     "lsi_hpr",     "dca_hpr",     100),
    ("CAGR (%)",    "lsi_cagr",    "dca_cagr",    100),
    ("Sharpe",      "lsi_sharpe",  "dca_sharpe",    1),
    ("Sortino",     "lsi_sortino", "dca_sortino",   1),
    ("W_final (€)", "lsi_w_final", "dca_w_final",   1),
]

rows = []
for freq, label in FREQ_CONFIGS:
    df = runs[freq]["results"]
    for metric_label, col_lsi, col_dca, scale in METRICS:
        lsi_v = df[col_lsi].dropna() * scale
        dca_v = df[col_dca].dropna() * scale
        rows.append({
            "Fréquence DCA" : label,
            "Métrique"      : metric_label,
            "LSI mean"      : lsi_v.mean(),
            "LSI std"       : lsi_v.std(),
            "LSI median"    : lsi_v.median(),
            "DCA mean"      : dca_v.mean(),
            "DCA std"       : dca_v.std(),
            "DCA median"    : dca_v.median(),
            "Δ mean (LSI−DCA)" : lsi_v.mean() - dca_v.mean(),
            "LSI wins (%)"  : (df[col_lsi] > df[col_dca]).mean() * 100,
        })

import pandas as pd
table = (
    pd.DataFrame(rows)
    .set_index(["Fréquence DCA", "Métrique"])
)

# ── 3. Affichage console ─────────────────────────────────────────
pd.set_option("display.float_format", "{:,.3f}".format)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 140)
print("\n")
print(table.to_string())







import pandas as pd

# =============================================================================
# CONFIGURATION GÉNÉRALE ET CONSTITUANTS DU CAC 40
# =============================================================================
CAC40_TICKERS = {
    "Air Liquide"        : "AI.PA",
    "Airbus"             : "AIR.PA",
    "ArcelorMittal"      : "MT.PA",
    "AXA"                : "CS.PA",
    "BNP Paribas"        : "BNP.PA",
    "Bouygues"           : "EN.PA",
    "Capgemini"          : "CAP.PA",
    "Carrefour"          : "CA.PA",
    "Crédit Agricole"    : "ACA.PA",
    "Danone"             : "BN.PA",
    "Dassault Systèmes"  : "DSY.PA",
    "Engie"              : "ENGI.PA",
    "EssilorLuxottica"   : "EL.PA",
    "Hermès"             : "RMS.PA",
    "Kering"             : "KER.PA",
    "Legrand"            : "LR.PA",
    "L'Oréal"            : "OR.PA",
    "LVMH"               : "MC.PA",
    "Michelin"           : "ML.PA",
    "Orange"             : "ORA.PA",
    "Pernod Ricard"      : "RI.PA",
    "Publicis"           : "PUB.PA",
    "Renault"            : "RNO.PA",
    "Safran"             : "SAF.PA",
    "Saint-Gobain"       : "SGO.PA",
    "Sanofi"             : "SAN.PA",
    "Schneider Electric" : "SU.PA",
    "Société Générale"   : "GLE.PA",
    "Stellantis"         : "STLAM.MI",
    "STMicroelectronics" : "STM.PA",
    "Teleperformance"    : "TEP.PA",
    "Thales"             : "HO.PA",
    "TotalEnergies"      : "TTE.PA",
    "Unibail-Rodamco"    : "URW.PA",
    "Veolia"             : "VIE.PA",
    "Vinci"              : "DG.PA",
    "Vivendi"            : "VIV.PA",
    "Worldline"          : "WLN.PA",
    "Accor"              : "AC.PA",
    "Eurofins"           : "ERF.PA",
}

FREQ_CONFIGS = [
    ("M",  "DCA mensuel  (12×/an)"),
    ("S",  "DCA semestriel (2×/an)"),
    ("A",  "DCA annuel    (1×/an)"),
]

METRICS = [
    ("HPR (%)",     "lsi_hpr",     "dca_hpr",     100),
    ("CAGR (%)",    "lsi_cagr",    "dca_cagr",    100),
    ("Sharpe",      "lsi_sharpe",  "dca_sharpe",    1),
    ("Sortino",     "lsi_sortino", "dca_sortino",   1),
    ("W_final (€)", "lsi_w_final", "dca_w_final",   1),
]

# Configuration de base pour Pandas
pd.set_option("display.float_format", "{:,.3f}".format)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 140)

# =============================================================================
# BOUCLE AUTOMATIQUE SUR TOUTES LES ACTIONS
# =============================================================================
for company_name, ticker in CAC40_TICKERS.items():
    print("\n" + "="*80)
    print(f" ANALYSE MULTI-FRÉQUENCE : {company_name.upper()} ({ticker})")
    print("="*80)

    # Dictionnaire de paramètres de base pour l'actif en cours
    COMMON = dict(
        ticker_str   = ticker,
        w0           = 12000,
        t0_str       = "2010-01-04",
        window_years = 5,
        shift_months = 1,
        n_windows    = 60,
        rf_annual    = 0.02,
        alpha        = 0.05,
        verbose      = False,
    )

    # 1. Collecte des backtests pour les 3 fréquences
    runs = {}
    skip_asset = False
    for freq, label in FREQ_CONFIGS:
        try:
            # Appel direct de ton vrai moteur de calcul
            runs[freq] = main_comparison(**COMMON, dca_freq=freq)
        except Exception as e:
            print(f"Erreur de calcul pour {ticker} en fréquence {freq}: {e}")
            skip_asset = True
            break

    if skip_asset:
        continue

    # 2. Extraction des statistiques et calcul des lignes
    rows = []
    for freq, label in FREQ_CONFIGS:
        df = runs[freq]["results"]
        for metric_label, col_lsi, col_dca, scale in METRICS:
            lsi_v = df[col_lsi].dropna() * scale
            dca_v = df[col_dca].dropna() * scale

            rows.append({
                "Fréquence DCA" : label,
                "Métrique"      : metric_label,
                "LSI mean"      : lsi_v.mean(),
                "LSI std"       : lsi_v.std(),
                "LSI median"    : lsi_v.median(),
                "DCA mean"      : dca_v.mean(),
                "DCA std"       : dca_v.std(),
                "DCA median"    : dca_v.median(),
                "Δ mean (LSI−DCA)" : lsi_v.mean() - dca_v.mean(),
                "LSI wins (%)"  : (df[col_lsi] > df[col_dca]).mean() * 100,
            })

    # 3. Construction et affichage immédiat de la structure DataFrame
    table_action = pd.DataFrame(rows).set_index(["Fréquence DCA", "Métrique"])
    print(table_action.to_string())

table_action



import pandas as pd

# =============================================================================
# CONFIGURATION GÉNÉRALE ET CONSTITUANTS DU CAC 40
# =============================================================================
CAC40_TICKERS = {
    "Air Liquide"        : "AI.PA",
    "Airbus"             : "AIR.PA",
    "ArcelorMittal"      : "MT.PA",
    "AXA"                : "CS.PA",
    "BNP Paribas"        : "BNP.PA",
    "Bouygues"           : "EN.PA",
    "Capgemini"          : "CAP.PA",
    "Carrefour"          : "CA.PA",
    "Crédit Agricole"    : "ACA.PA",
    "Danone"             : "BN.PA",
    "Dassault Systèmes"  : "DSY.PA",
    "Engie"              : "ENGI.PA",
    "EssilorLuxottica"   : "EL.PA",
    "Hermès"             : "RMS.PA",
    "Kering"             : "KER.PA",
    "Legrand"            : "LR.PA",
    "L'Oréal"            : "OR.PA",
    "LVMH"               : "MC.PA",
    "Michelin"           : "ML.PA",
    "Orange"             : "ORA.PA",
    "Pernod Ricard"      : "RI.PA",
    "Publicis"           : "PUB.PA",
    "Renault"            : "RNO.PA",
    "Safran"             : "SAF.PA",
    "Saint-Gobain"       : "SGO.PA",
    "Sanofi"             : "SAN.PA",
    "Schneider Electric" : "SU.PA",
    "Société Générale"   : "GLE.PA",
    "Stellantis"         : "STLAM.MI",
    "STMicroelectronics" : "STM.PA",
    "Teleperformance"    : "TEP.PA",
    "Thales"             : "HO.PA",
    "TotalEnergies"      : "TTE.PA",
    "Unibail-Rodamco"    : "URW.PA",
    "Veolia"             : "VIE.PA",
    "Vinci"              : "DG.PA",
    "Vivendi"            : "VIV.PA",
    "Worldline"          : "WLN.PA",
    "Accor"              : "AC.PA",
    "Eurofins"           : "ERF.PA",
}

FREQ_CONFIGS = [
    ("M",  "DCA mensuel  (12×/an)"),
    ("S",  "DCA semestriel (2×/an)"),
    ("A",  "DCA annuel    (1×/an)"),
]

METRICS = [
    ("HPR (%)",     "lsi_hpr",     "dca_hpr",     100),
    ("CAGR (%)",    "lsi_cagr",    "dca_cagr",    100),
    ("Sharpe",      "lsi_sharpe",  "dca_sharpe",    1),
    ("Sortino",     "lsi_sortino", "dca_sortino",   1),
    ("W_final (€)", "lsi_w_final", "dca_w_final",   1),
]

# Configuration de base pour Pandas
pd.set_option("display.float_format", "{:,.3f}".format)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 140)

# Nom du fichier Excel de sortie
output_excel_file = "Backtest_LSI_vs_DCA_CAC40.xlsx"

# =============================================================================
# BOUCLE AUTOMATIQUE SUR TOUTES LES ACTIONS ET EXPORT EXCEL
# =============================================================================
# Utilisation de pd.ExcelWriter pour tout centraliser dans un seul fichier
with pd.ExcelWriter(output_excel_file, engine="openpyxl") as writer:

    for company_name, ticker in CAC40_TICKERS.items():
        print("\n" + "="*80)
        print(f" ANALYSE MULTI-FRÉQUENCE : {company_name.upper()} ({ticker})")
        print("="*80)

        # Dictionnaire de paramètres de base pour l'actif en cours
        COMMON = dict(
            ticker_str   = ticker,
            w0           = 12000,
            t0_str       = "2010-01-04",
            window_years = 5,
            shift_months = 1,
            n_windows    = 60,
            rf_annual    = 0.02,
            alpha        = 0.05,
            verbose      = False,
        )

        # 1. Collecte des backtests pour les 3 fréquences
        runs = {}
        skip_asset = False
        for freq, label in FREQ_CONFIGS:
            try:
                # Appel direct de ton vrai moteur de calcul
                runs[freq] = main_comparison(**COMMON, dca_freq=freq)
            except Exception as e:
                print(f"Erreur de calcul pour {ticker} en fréquence {freq}: {e}")
                skip_asset = True
                break

        if skip_asset:
            continue

        # 2. Extraction des statistiques et calcul des lignes
        rows = []
        for freq, label in FREQ_CONFIGS:
            df = runs[freq]["results"]
            for metric_label, col_lsi, col_dca, scale in METRICS:
                lsi_v = df[col_lsi].dropna() * scale
                dca_v = df[col_dca].dropna() * scale

                rows.append({
                    "Fréquence DCA" : label,
                    "Métrique"      : metric_label,
                    "LSI mean"      : lsi_v.mean(),
                    "LSI std"       : lsi_v.std(),
                    "LSI median"    : lsi_v.median(),
                    "DCA mean"      : dca_v.mean(),
                    "DCA std"       : dca_v.std(),
                    "DCA median"    : dca_v.median(),
                    "Δ mean (LSI−DCA)" : lsi_v.mean() - dca_v.mean(),
                    "LSI wins (%)"  : (df[col_lsi] > df[col_dca]).mean() * 100,
                })

        # 3. Construction et affichage de la structure DataFrame
        table_action = pd.DataFrame(rows).set_index(["Fréquence DCA", "Métrique"])
        print(table_action.to_string())

        # 4. Nettoyage du nom du ticker pour respecter la limite Excel de 31 caractères par onglet
        sheet_name = ticker.replace("/", "_")[:31]

        # 5. Écriture dans l'onglet correspondant
        table_action.to_excel(writer, sheet_name=sheet_name)

print(f"\n[SUCCÈS] Tous les résultats ont été exportés dans le fichier : {output_excel_file}")





